### ISSUE TITLE
Custom Fields with custom content table not adding their values to the customFields key during ElementQuery::createElement

### ISSUE THREAD

**Issue by Anubarak** [craftcms/cms#10622]
### Description
I have a custom field that has it's values in a custom table but I left join this custom table in my fields `modifyElementsQuery` method. I added an `addSelect` there as well. So in Craft 3.7.26 everything went well. In a certain Craft version you added the [following](https://github.com/craftcms/cms/blob/develop/src/elements/db/ElementQuery.php#L1902)
```PHP
    if (!empty($this->customFields)) {
        foreach ($this->customFields as $field) {
            if (($column = $this->_fieldColumn($field)) !== null) {
```
Since my custom field has no contentColumn `$column` is now null, but I cannot set this one to `true` because it breaks other things.
I could create a custom behavior with this attribute just to hide the error but that seems stupid to me.

To "hide" the error I included the following check
```PHP
 if (($column = $this->_fieldColumn($field)) !== null || ($field implements CustomTableInterface && $column = $field->getColumnName() !== null) {
```
Your `Element::__set` function will set the field value only if the field is in the elements field layout

```PHP
    /**
     * @inheritdoc
     */
    public function __set($name, $value)
    {
        // Is this the "field:handle" syntax?
        if (strncmp($name, 'field:', 6) === 0) {
            $this->setFieldValue(substr($name, 6), $value);
            return;
        }

        try {
            parent::__set($name, $value);
        } catch (InvalidCallException | UnknownPropertyException $e) {
            // Is this is a field?
            if ($this->fieldByHandle($name) !== null) {
                $this->setFieldValue($name, $value);
            } else {
                throw $e;
            }
        }
    }
```
This might not always the case for each section/entrytype so there is no real way except via behavior to "fix" this.

### Steps to reproduce

1. Store Field values in a custom table and try to left join their information
2. the field values are not set into the `$row['fieldValues'] = $fieldValues;` key, thus an exception is thrown because the attribute cannot be set.

### Steps to solve

- I could either create a custom behavior that just checks if the set value is a custom field but not in the layout to swallow the error.
- You could include an extra check if the field want's to set a custom column name.
- create an `EVENT_BEFORE_POPULATE_ELEMENT` in order to let me change the `$row` variable before `new $class($row)` is called
### Additional info

I submitted it as a bug, because it's a kinda breaking change. Even tho I guess my way was not intended I frequently joined other tables and set field values that way in order to "safe" an additional Query during my `isEmpty` call because I already have the ID in that case.
- Craft version: 3.7.33 (even tho I didn't search when the change was made)

**Comment by Anubarak** [comment]
I have to correct myself.
The issue starts in version 3.7.21
3.7.20 -> everything is fine
3.7.21 -> exception

The source is in `yii\base\Component` I added the following Code exactly [there](https://github.com/yiisoft/yii2/blob/2.0.40/framework/base/Component.php#L200)

```PHP
if($name === 'sequenceId'){
    echo "<pre>";
    var_dump($behavior::class");
    var_dump($behavior->canSetProperty($name));
    echo "</pre>";
    die();
}
```

### Result for Craft 3.7.20
```
string(35) "craft\behaviors\CustomFieldBehavior"
bool(true)
```
### Result for Craft 3.7.21
```
string(35) "craft\behaviors\CustomFieldBehavior"
bool(false)
```

The Yii2 Version does not change,

**Comment by Anubarak** [comment]
Found it
https://github.com/craftcms/cms/blob/3.7.21/src/base/Element.php#L1782
```PHP
    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['customFields'] = [
            'class' => CustomFieldBehavior::class,
            'canSetProperties' => false,
        ];
        return $behaviors;
    }
```
this makes it impossible to add custom fields during population

**Comment by brandonkelly** [comment]
> Your `Element::__set` function will set the field value only if the field is in the elements field layout

Missed this before, but that is indeed the “issue” here.

Before 3.7.21, setting custom field values via `$element->myFieldHandle = 'x'` wasn’t reliable, because the value would get set on `CustomFieldBehavior` without the element ever knowing about it. If the particular field’s value had already been retrieved and normalized, then the new value you set on it would still be considered normalized and would not get run through the field’s `normalizeValue()` method the next time it was retrieved.

For example:

```php
var_dump($entry->CheckboxesField);

// Output:
// class craft\fields\data\MultiOptionsFieldData#2907 (2) {
//   private $_options =>
//   array(3) {
//     [0] =>
//     string(3) "foo"
//     [1] =>
//     string(3) "bar"
//     [2] =>
//     string(3) "baz"
//   }
//   private $storage =>
//   array(1) {
//     [0] =>
//     string(3) "foo"
//   }
// }

$entry->myCheckboxesField = ['foo', 'bar'];
var_dump($entry->CheckboxesField);

// Output:
// array(2) {
//   [0] =>
//   string(3) "foo"
//   [1] =>
//   string(3) "bar"
// }
```

(The only reliable way to actually do it was to go through `setFieldValue()`.)

We fixed that in 3.7.21 by disallowing properties from getting set on the behavior via `craft\base\Element::_set()`. (#7726) So now this code (which was there already, but pointless pre-3.7.21) will now work as intended:

https://github.com/craftcms/cms/blob/6d9bcd3bed7e84c4d17b836825f57b970367b7b8/src/base/Element.php#L1778-L1781

A side effect of this change is that `__set()` is now more strict about only allowing fields that actually belong to the element’s field layout to be set that way, whereas previously any field that had a corresponding property on `CustomFieldBehavior` was technically settable (but again, it was unreliable and not supported).

I would say that is definitely working as expected now though. You should be able to solve your issue by adding the field to the field layout.

**Comment by Anubarak** [comment]
But that would mean I would have to include the field for each field layout. Otherwise it would still throw exceptions.

I guess creating a behavior that swallows the exception is a better alternative. In case no field is found it the layout it will just set it there.

**Comment by Anubarak** [comment]
Nono I mean I get these errors for elements that have these fields not in the layout. The query doesn't know what layouts the elements have. 

Example: I have a section with 2 entry types. One type has the field, another one not. When I fetch all entries in this section (or just the element index page for all sections) the column is selected thus elements will be populated with that field. They'll all have null values but craft tries to populate them -> exception.

The only way to prevent that without a behavior is to add the field to every single layout.

**Comment by brandonkelly** [comment]
Ahh, got it!

I’ve just made a little change that will fix this for you: we’re no longer setting `canSetProperties => false` until the first time a field value is normalized. So elements will be less strict initially when being populated from the element query.
