### ISSUE TITLE
[4.x]: GraphQL mutation "Author Id cannot be blank."

### ISSUE THREAD

**Issue by ardin0546** [craftcms/cms#11312]
### Description
I created a very basic entry named `posts`. The type of the entry is `channel` and it only has one basic field named `title`. 
With GrapQL I am trying to insert a single post entry. When I do this outside craft (for example with postman) I get the error message `Author Id cannot be blank.`.

This is the query what I'm trying to execute. User `21` exists in the database. 
![Schermafbeelding 2022-05-25 om 11 31 26](https://user-images.githubusercontent.com/22168410/170230719-b782dec6-bc37-487f-8e0d-127f4e6ebbb4.png)

**I checked also the following in my Public schema:
![Schermafbeelding 2022-05-25 om 11 26 17](https://user-images.githubusercontent.com/22168410/170229700-59832daa-045b-498a-a4e4-1fe782e17564.png)**

I also tried with a private schema and a Bearer token and then my error message is `Cannot query field \"authorId\" on type \"posts_default_Entry\".`

However, when I'm doing the exact same query in the `GraphQL Explorer` inside craft, I am able to create a post. Only the `authorId` is not set to the expected `21 (normal user)`. But to my current session user `1 (admin user)`.

Query:
![Schermafbeelding 2022-05-25 om 11 34 51](https://user-images.githubusercontent.com/22168410/170231483-651fe506-d4a3-4d44-9581-68d3a0ea7e8e.png)

Result:
![Schermafbeelding 2022-05-25 om 11 35 41](https://user-images.githubusercontent.com/22168410/170231687-992a1de6-95ae-49c0-9cdf-b1d1aea32b22.png)

And in the [docs](https://craftcms.com/docs/4.x/graphql.html#mutating-entries) it's written that I am able to send `authorId` as parameter.  

### Steps to reproduce

1. Upgrade craft to a PRO trial license
2. Create a new section. Title: `Posts`, handle: `posts`, Section type: `channel`, Now the section has a Default entry type and a default field `title`.
3. Under `GraphQL -> Schemas -> Plublic Schema -> Choose the available mutations for this schema`, check everything related to `Section - posts` 
4. In your `config/routes.php` add: `'api' => 'graphql/api',`
5. Create a POST request with for example postman and execute the query from the description to endpoint `{yourSite}/api`

### Expected behavior

A post is created with that `authorId`

### Actual behavior
Error message: `Author Id cannot be blank.` or `Cannot query field \"authorId\" on type \"posts_default_Entry\".`

### Craft CMS version

4.0.3

### PHP version

8.0.19

### Operating system and version

Darwin 20.1.0

### Database type and version

MySQL 8.0.29

### Image driver and version

GD 8.0.19

**Comment by brandonkelly** [comment]
The issue is most likely that you are trying to return the resulting entry’s `authorId`, which is only available if your schema includes **Users** → **View all users**. Without that, no user-related info will be available.

**Comment by ardin0546** [comment]
Nope, ` Users → View all users` was also set...

**Comment by brandonkelly** [comment]
Sorry, looked into it again using an external GraphQL IDE and was able to reproduce. Fixed now for the next release!

**Comment by stuible** [comment]
Thanks a ton for fixing this so quickly, Is there an ETA for this next release?

**Comment by brandonkelly** [comment]
Should be imminent.

**Comment by brandonkelly** [comment]
Craft 4.0.4 is out now with that fix.

**Comment by dande-sun** [comment]
Hello @brandonkelly, I think this issue is back, I use the GraphQL mutation to save a entry in CMS tool, is completed. but when I use the nodejs fetch to save the same entry, I got the error `Author Id cannot be blank.`, and I have give it the entry authorId, but I think it need is the element revision authorId,

Craft CMS: 4.16.12

**Comment by dande-sun** [comment]
![Image](https://github.com/user-attachments/assets/721a8209-7bd6-42b5-89ff-e0185ccbe3ee)
![Image](https://github.com/user-attachments/assets/cb11e98a-0696-4e03-8a10-bda2b614d090)

```
2025-10-29 05:12:44 [web.ERROR] [GraphQL\Error\UserError] GraphQL\Error\UserError: Author Id cannot be blank.
The selected entries contain validation errors, preventing this entry from being saved. Edit the entries to fix them. in /craft-cms/vendor/craftcms/cms/src/gql/base/ElementMutationResolver.php:188
Stack trace:
#0 /craft-cms/vendor/craftcms/cms/src/gql/resolvers/mutations/Entry.php(85): craft\gql\base\ElementMutationResolver->saveElement(Object(craft\elements\Entry))
#1 /craft-cms/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(623): craft\gql\resolvers\mutations\Entry->saveEntry(NULL, Array, Array, Object(GraphQL\Type\Definition\ResolveInfo))
#2 /craft-cms/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(550): GraphQL\Executor\ReferenceExecutor->resolveFieldValueOrError(Object(GraphQL\Type\Definition\FieldDefinition), Object(GraphQL\Language\AST\FieldNode), Array, NULL, Object(GraphQL\Type\Definition\ResolveInfo))
#3 /craft-cms/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(474): GraphQL\Executor\ReferenceExecutor->resolveField(Object(GraphQL\Type\Definition\ObjectType), NULL, Object(ArrayObject), Array)
#4 /craft-cms/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(857): GraphQL\Executor\ReferenceExecutor->GraphQL\Executor\{closure}(Array, 'save_news_defau...')
#5 [internal function]: GraphQL\Executor\ReferenceExecutor->GraphQL\Executor\{closure}(Array, 'save_news_defau...')
#6 /craft-cms/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(859): array_reduce(Array, Object(Closure), Array)
#7 /craft-cms/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(490): GraphQL\Executor\ReferenceExecutor->promiseReduce(Array, Object(Closure), Array)
#8 /craft-cms/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(263): GraphQL\Executor\ReferenceExecutor->executeFieldsSerially(Object(GraphQL\Type\Definition\ObjectType), NULL, Array, Object(ArrayObject))
#9 /craft-cms/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(215): GraphQL\Executor\ReferenceExecutor->executeOperation(Object(GraphQL\Language\AST\OperationDefinitionNode), NULL)
#10 /craft-cms/vendor/webonyx/graphql-php/src/Executor/Executor.php(156): GraphQL\Executor\ReferenceExecutor->doExecute()
#11 /craft-cms/vendor/webonyx/graphql-php/src/GraphQL.php(162): GraphQL\Executor\Executor::promiseToExecute(Object(GraphQL\Executor\Promise\Adapter\SyncPromiseAdapter), Object(GraphQL\Type\Schema), Object(GraphQL\Language\AST\DocumentNode), NULL, Array, Array, NULL, NULL)
#12 /craft-cms/vendor/webonyx/graphql-php/src/GraphQL.php(94): GraphQL\GraphQL::promiseToExecute(Object(GraphQL\Executor\Promise\Adapter\SyncPromiseAdapter), Object(GraphQL\Type\Schema), 'mutation ($slug...', NULL, Array, Array, NULL, NULL, Array)
#13 /craft-cms/vendor/craftcms/cms/src/services/Gql.php(515): GraphQL\GraphQL::executeQuery(Object(GraphQL\Type\Schema), 'mutation ($slug...', NULL, Array, Array, NULL, NULL, Array)
#14 /craft-cms/vendor/craftcms/cms/src/controllers/GraphqlController.php(195): craft\services\Gql->executeQuery(Object(craft\models\GqlSchema), 'mutation ($slug...', Array, NULL, true)
#15 [internal function]: craft\controllers\GraphqlController->actionApi()
#16 /craft-cms/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#17 /craft-cms/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#18 /craft-cms/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('api', Array)
#19 /craft-cms/vendor/craftcms/cms/src/web/Application.php(349): yii\base\Module->runAction('graphql/api', Array)
#20 /craft-cms/vendor/craftcms/cms/src/web/Application.php(648): craft\web\Application->runAction('graphql/api', Array)
#21 /craft-cms/vendor/craftcms/cms/src/web/Application.php(311): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#22 /craft-cms/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#23 /craft-cms/web/index.php(20): yii\base\Application->run()
#24 {main} {"trace":[{"file":"/craft-cms/vendor/craftcms/cms/src/services/Gql.php","line":1205,"function":"logException","class":"yii\\base\\ErrorHandler","type":"->"},{"file":"/craft-cms/vendor/webonyx/graphql-php/src/Executor/ExecutionResult.php","line":147,"function":"handleQueryErrors","class":"craft\\services\\Gql","type":"->"},{"file":"/craft-cms/vendor/craftcms/cms/src/services/Gql.php","line":518,"function":"toArray","class":"GraphQL\\Executor\\ExecutionResult","type":"->"}],"memory":94143000,"exception":"[object] (GraphQL\\Error\\UserError(code: 0): Author Id cannot be blank.
```

**Comment by brandonkelly** [comment]
Hi @dande-sun, unfortunately I can’t reproduce this time. I’m able to create entries via an external GraphQL client without any problems.

<img width="2186" height="1328" alt="Image" src="https://github.com/user-attachments/assets/6582d4c8-5153-4a71-b0ec-e9e1881ccf0b" />

Try updating to the latest release, and if you’re still having issues, please send your database backup and Composer files into support@craftcms.com, along with the query you’re attempting, and we can look into it on our end.
