### ISSUE TITLE
[4.x]: 'Generating pending image transforms' jobs are all repeating the same work

### ISSUE THREAD

**Issue by FlorisDerks** [craftcms/cms#12274]
### Description

When the generateTransformsBeforePageLoad setting isn't set to TRUE, jobs are queued to generate pending transforms. However, these jobs seem to all do the same work when running concurrently, even though there is a 'inProgess' column in the imagetransformindex table.

Since all jobs do the same work, and don't reserve an image prior to starting the transform, all jobs come to a halt when a single image transform fails, as can be seen on this screenshot:

![Schermafbeelding 2022-11-08 om 10 39 48](https://user-images.githubusercontent.com/1500538/200541100-1a2f84b1-1d07-42bd-81f6-78f2980c0320.png)

### Steps to reproduce

1. Disable all queue-workers
2. Gather some pending image transforms by clicking around the site or CMS
3. Start multiple queue-workers
4. See that they all try to resize the same images, even when they are already completed by another worker, and they all hang on the same longer-lasting images which they all try to complete at the same time.

### Expected behavior

Image transforms are only handled by a single job at the same time, and are reserved to that worker when starting. Since a job is added for every single pending image transform, maybe that job should only handle that specific image instead of the whole queue in every job?

### Actual behavior

Image transforms are only handled as completed when all image transforms in the job are completed.

### Craft CMS version

v4.3.1

### PHP version

8.0

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
This has been addressed in two ways:

- The “Generating pending image transforms” job has been updated for the next Craft 3 and 4 releases, to completely ignore any transforms that have already been generated or are currently in progress. (Previously the job would fetch all pending transforms up front, and then attempt to process each of them, including any transforms that were already processed by a separate request between the time the job started and whenever it got around to that transform.)
- That job is deprecated for Craft 4.4, in favor of a new “Generating image transform” (singular) job, which will be queued up for each ungenerated transform that is requested. This will result in significantly _more_ jobs getting queued, but each of them will be significantly faster, reducing the likelihood that Craft will run out of resources mid-job. (The jobs will also bail immediately if their transform already exists by the time they’re executed.)

**Comment by realjoshharrison** [comment]
@brandonkelly @i-just... is there a way to get this fix early, along with the fix for #12504?

Just so happens I'm working on an image transform heavy horizontally scrolling site..! 

Thanks 😊

**Comment by brandonkelly** [comment]
Craft 3.7.64 and 4.3.7 have been released with that first fix.

**Comment by Bronskiy** [comment]
Looks like the problem is back in 4.5.10
![image](https://github.com/craftcms/cms/assets/1948199/2928f0d4-d0fb-4ae9-9c3f-0b9ac5e97981)

**Comment by marina-moca** [comment]
Confirm we are seeing this too on 4.5.10

![CleanShot 2023-11-15 at 12 13 20 2](https://github.com/craftcms/cms/assets/56370392/6ce928a7-f1b3-42e1-b94b-9a6df30bf686)

Is there any way we can disable the firing of the queue processing on login (given we have a cron job periodically running the queue process (ie * * * * * flock -n /container/application/queue.lock /usr/local/bin/php /container/application/craft queue/run >/dev/null 2>&1)

Thanks

**Comment by realjoshharrison** [comment]
> Is there any way we can disable the firing of the queue processing on login (given we have a cron job periodically running the queue process (ie * * * * * flock -n /container/application/queue.lock /usr/local/bin/php /container/application/craft queue/run >/dev/null 2>&1)

[`GeneralConfig::$runQueueAutomatically`](https://docs.craftcms.com/api/v4/craft-config-generalconfig.html#runqueueautomatically) sounds like what you need for that?

**Comment by Bronskiy** [comment]
> > Is there any way we can disable the firing of the queue processing on login (given we have a cron job periodically running the queue process (ie * * * * * flock -n /container/application/queue.lock /usr/local/bin/php /container/application/craft queue/run >/dev/null 2>&1)
> 
> [GeneralConfig::$runQueueAutomatically](https://docs.craftcms.com/api/v4/craft-config-generalconfig.html#runqueueautomatically) sounds like what you need for that:
> 
> Add to `config/general.php`: `->runQueueAutomatically(false)`
> 
> Or, add to `.env`: `CRAFT_RUN_QUEUE_AUTOMATICALLY=false`

in such case it just adds new line with Pending status every second

**Comment by marina-moca** [comment]
Thanks for the responses. Should we be logging this as a new job - I notice this one is closed....

**Comment by Bronskiy** [comment]
@brandonkelly could you reopen the issue?

**Comment by brandonkelly** [comment]
@Bronskiy It looks like you are describing the expected behavior, if you read my previous comment (https://github.com/craftcms/cms/issues/12274#issuecomment-1377755951).

**Comment by marina-moca** [comment]
Hi, ok it's Sunday here and I'm on our dev system so no other activity. I have added a video of what happens each time I log in and navigate to an item in the sidebar. Note it only starts queuing transformation when I click on something.

https://share.cleanshot.com/jZ1vCbH7

I've also noted the load on the container (it's all transformation load) so this is not an insignificant process especially when we will have up to 10 people logged in to the backend at any one time once the system is live.

I also note we have maybe 30 other CraftCMS sites where we don't see this behaviour, although this is the most complicated with 8 sites within the multisite setup.

So it could be we are an edge case, but this behaviour is not expected or desired. Any help on this would be much appreciated - maybe I should be logging it somewhere else?

Thanks.

**Comment by Bronskiy** [comment]
> @Bronskiy It looks like you are describing the expected behavior, if you read my previous comment ([#12274 (comment)](https://github.com/craftcms/cms/issues/12274#issuecomment-1377755951)).

yes, but it looks like it generates it unlimited

**Comment by marina-moca** [comment]
Hi, further to this, we cleared out some data yesterday and re-imported - the problem no longer exists, so we are wondering if one of our previous imports had some issues with images. Not sure, but we are not longer seeing any transforming of images as per my video above. Fingers crossed it stays this way.

Cheers!

**Comment by danethomas** [comment]
We're seeing this on 4.5.10 and I've just upgraded to 4.7.1 and it seems to be continuing. Continual Generating image transform jobs getting created with the job data 

```
{
    "description": null,
    "transformId": 1
}
```

I suspect it's something that's gone wrong with a `imagetransformindex` record. I'll try to re-index assets from the CP to see if that fixes anything (it didn't on 4.5.10) - anything that you can suggest either via the CP or CLI?

**Comment by danethomas** [comment]
@marina-moca when you say you cleared our some data and re-imported - what did you do? We're still trying to get to the bottom of this issue for our instance.

**Comment by danethomas** [comment]
This ended up being related to SEOMatic and a site default meta image (gif) not having transforms enabled on it. Turned that setting on and the jobs stopped queueing.

**Comment by AmarHuda1** [comment]
> Confirm we are seeing this too on 4.5.10
> 
> ![CleanShot 2023-11-15 at 12 13 20 2](https://private-user-images.githubusercontent.com/56370392/283368853-6ce928a7-f1b3-42e1-b94b-9a6df30bf686.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4MTQ3NjAsIm5iZiI6MTcwNzgxNDQ2MCwicGF0aCI6Ii81NjM3MDM5Mi8yODMzNjg4NTMtNmNlOTI4YTctZjFiMy00MmUxLWI5NGItOWE2ZGYzMGJmNjg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEzVDA4NTQyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0Njc4MTkxNTljZWQ4YzU1MDkyNzg4ZDE5ZTliMzE1ZTlhODZlOWE2YzhhMzU1NDkxYWI1OGI3MDM3ZDcxN2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-u6_CG9L-HglLjJ7uOksrfxvhxARoPoCLLYmjz8SJ1U)
> 

if this kind of behaviour occurs in Production Environments will it affect the server performance? Like, it will cause server error or PHP-timeout?

**Comment by smockensturm** [comment]
Same. Half a million transforms queued overnight. (37 assets, 8 transforms)

Craft Pro 4.9.7
PHP 8.2.12

> if this kind of behaviour occurs in Production Environments, will it affect the server performance?

It sure did for us @AmarHuda1 . 4.5 million jobs in the queue table at one point. 503s all over the place. No CP access.

 What is happening here @brandonkelly ?

**Comment by Codesesh** [comment]
We had the same issue, too, where it kept running the image transforms. It turned out that it was a .svg that the client had uploaded as a favicon via SEOMatic backend settings, which caused the image transforms to continue running constantly. After the .svg was removed it stopped. Assuming .svg was rouge or maybe the SEOmatic code isn't handling it correctly.
