### ISSUE TITLE
[5.x]: Failed to install Craft 5 from scratch / COLLATION 'utf8mb4_0900_ai_ci' is not valid for CHARACTER SET 'utf8mb3'

### ISSUE THREAD

**Issue by mei-lu** [craftcms/cms#14027]
### Description
I am trying to set up a Craft 5 alpha instance from scratch, but am running into database issues. I don't quite understand where utf8mb3 is coming from, since it doesn't appear anywhere in my configurations. Thanks for looking into this for me!

### Steps to reproduce
1. Set up Craft from scratch with directions from [knowledge base](https://craftcms.com/knowledge-base/setting-up-a-craft-project-from-scratch)
2. Create a mysql database
3. Run `php craft setup`

error:
```
*** failed to install Craft: An error occurred while executing the "craft\migrations\Install migration: SQLSTATE[42000]: Syntax error or access violation: 1253 COLLATION 'utf8mb4_0900_ai_ci' is not valid for CHARACTER SET 'utf8mb3'
The SQL being executed was: CREATE TABLE `addresses` (
        `id` int(11) NOT NULL,
        `primaryOwnerId` int(11),
        `fieldId` int(11),
        `countryCode` varchar(255) NOT NULL,
        `administrativeArea` varchar(255),
        `locality` varchar(255),
        `dependentLocality` varchar(255),
        `postalCode` varchar(255),
        `sortingCode` varchar(255),
        `addressLine1` varchar(255),
        `addressLine2` varchar(255),
        `organization` varchar(255),
        `organizationTaxId` varchar(255),
        `fullName` varchar(255),
        `firstName` varchar(255),
        `lastName` varchar(255),
        `latitude` varchar(255),
        `longitude` varchar(255),
        `dateCreated` datetime(0) NOT NULL,
        `dateUpdated` datetime(0) NOT NULL,
        PRIMARY KEY(`id`)
) ENGINE = InnoDb DEFAULT CHARACTER SET = utf8 DEFAULT COLLATE = utf8mb4_0900_ai_ci
```

mysql database charset and collation (from mysql workbench)
![image](https://github.com/craftcms/cms/assets/52755821/8d66ceea-6380-4df0-8e29-b28ccebf3438)

mysql version:
`mysql  Ver 8.1.0 for macos13.3 on arm64 (Homebrew)`

db charset and collation from .env (this was autogenerated for me upon running `php craft setup`):
```
DB_CHARSET=utf8mb4
DB_COLLATION=utf8mb4_unicode_ci
```

composer.json:
```
{
    "require": {
        "craftcms/cms": "^5.0.x-dev",
        "vlucas/phpdotenv": "^5.6"
    },
    "require-dev": {
        "craftcms/generator": "2.0.x-dev",
        "yiisoft/yii2-shell": "^2.0.3"
    },
    "autoload": {
        "psr-4": {
            "modules\\": "modules/"
        }
    },
    "config": {
        "allow-plugins": {
            "yiisoft/yii2-composer": true,
            "craftcms/plugin-installer": true
            
        },
        "sort-packages": true,
        "optimize-autoloader": true,
        "platform": {
          "php": "8.2"
        }
    },
    "scripts": {
        "post-root-package-install": [
          "@php -r \"file_exists('.env') || copy('.env.example.dev', '.env');\""
        ]
    }
}
```

### Craft CMS version

5.0.x-dev

### PHP version

PHP 8.2.12

### Operating system and version

MacOS 13.6.1 (22G313)

### Database type and version

mysql 8.1.0 for macos13.3 on arm64 (Homebrew)

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reaching out!

I believe the `utf8mb3` is coming from the `ENGINE = InnoDb DEFAULT CHARACTER SET = utf8 DEFAULT COLLATE = utf8mb4_0900_ai_ci` part - at the end of the error you posted. 
`utf8` is still an alias for `utf8mb3`: https://dev.mysql.com/doc/refman/8.0/en/charset-unicode-utf8.html.

As a starting point, can you please check if you have the `config/db.php` file? If you do, check that it doesn’t contain `charset` and `collation`. If you don’t have that file, it’s ok.

Then, please change the `DB_CHARSET` to `CRAFT_DB_CHARSET` and `DB_COLLATION` to `CRAFT_DB_COLLATION`, rerun the setup command, and see if that helps.

**Comment by mei-lu** [comment]
@i-just Hi there, thanks for your response! I do not have the `config/db.php` file. Good to know about the aliasing!

I have tried changing the names with CRAFT in front as suggested, but running into the same error. I also run into the same error if I delete the `CRAFT_DB_CHARSET` and `CRAFT_DB_COLLATION` lines in my `.env`.

**Comment by mei-lu** [comment]
I was able to set up 5.0.0 alpha by first installing the latest version of Craft 4 and upgrading to 5.

1. Change composer.json to require `"craftcms/cms": "5.0.x-dev as 5.0.0-alpha"` and dev requirement `"craftcms/generator": "2.0.x-dev"`
2. `composer update`
3. `php craft up`

**Comment by i-just** [comment]
I wasn’t able to reproduce the error you were getting, but I’m glad to hear you managed to set it up!

It’s probably worth noting that MySQL 8.1 was an [innovation release](https://blogs.oracle.com/mysql/post/introducing-mysql-innovation-and-longterm-support-lts-versions), and it’s already [no longer supported](https://endoflife.date/mysql), so you might want to consider moving to the 8.0 LTS version.

I’m going to close this now, but if you run into further issues, please don’t hesitate to get in touch.

**Comment by brandonkelly** [comment]
@lindseydiloreto Did the SQL query contain `CHARACTER SET = utf8` like in the original post?

The `charset` setting is set to `utf8` by default, but that is supposed to get normalized to `utf8mb4` for MySQL/MariaDB:

https://github.com/craftcms/cms/blob/a18a4cbc5f2871e2cc12a99c9ff9a1be61e941e9/src/config/DbConfig.php#L336-L342

https://github.com/craftcms/cms/blob/a18a4cbc5f2871e2cc12a99c9ff9a1be61e941e9/src/config/DbConfig.php#L402-L408

Do you have a `config/db.php` file set? If so can you post the contents of it?

**Comment by lindseydiloreto** [comment]
Here's the `config/db.php` file, it's part of the boilerplate we've been using for years...

```php
return [
    'server'   => getenv('DB_HOSTNAME'),
    'database' => getenv('DB_DATABASE'),
    'user'     => getenv('DB_USERNAME'),
    'password' => getenv('DB_PASSWORD'),
];
```

Here is the complete error message when I'm installing Craft 5 from scratch (using existing .env and project config files)...

```
Email: test@example.com
Password: 
Confirm: 
Site name: [$BUSINESS_NAME] 
Site URL: [$SITE_BASEURL] 
Site language: [en-US] 
*** installing Craft
    > create table {{%addresses}} ...Exception: SQLSTATE[42000]: Syntax error or access violation: 1253 COLLATION 'utf8mb4_0900_ai_ci' is not valid for CHARACTER SET 'utf8mb3'
The SQL being executed was: CREATE TABLE `addresses` (
        `id` int(11) NOT NULL,
        `primaryOwnerId` int(11),
        `fieldId` int(11),
        `countryCode` varchar(255) NOT NULL,
        `administrativeArea` varchar(255),
        `locality` varchar(255),
        `dependentLocality` varchar(255),
        `postalCode` varchar(255),
        `sortingCode` varchar(255),
        `addressLine1` varchar(255),
        `addressLine2` varchar(255),
        `addressLine3` varchar(255),
        `organization` varchar(255),
        `organizationTaxId` varchar(255),
        `fullName` varchar(255),
        `firstName` varchar(255),
        `lastName` varchar(255),
        `latitude` varchar(255),
        `longitude` varchar(255),
        `dateCreated` datetime(0) NOT NULL,
        `dateUpdated` datetime(0) NOT NULL,
        PRIMARY KEY(`id`)
) ENGINE = InnoDb DEFAULT CHARACTER SET = utf8 DEFAULT COLLATE = utf8mb4_0900_ai_ci (/var/www/html/vendor/yiisoft/yii2/db/Schema.php:676)
#0 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1307): yii\db\Schema->convertException(Object(PDOException), 'CREATE TABLE `a...')
#1 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1102): yii\db\Command->internalExecute('CREATE TABLE `a...')
#2 /var/www/html/vendor/yiisoft/yii2/db/Migration.php(322): yii\db\Command->execute()
#3 /var/www/html/vendor/craftcms/cms/src/migrations/Install.php(95): yii\db\Migration->createTable('{{%addresses}}', Array)
#4 /var/www/html/vendor/craftcms/cms/src/migrations/Install.php(74): craft\migrations\Install->createTables()
#5 /var/www/html/vendor/craftcms/cms/src/db/Migration.php(49): craft\migrations\Install->safeUp()
#6 /var/www/html/vendor/craftcms/cms/src/db/MigrationManager.php(233): craft\db\Migration->up(true)
#7 /var/www/html/vendor/craftcms/cms/src/console/controllers/InstallController.php(213): craft\db\MigrationManager->migrateUp(Object(craft\migrations\Install))
#8 [internal function]: craft\console\controllers\InstallController->actionCraft()
#9 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#10 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#11 /var/www/html/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction('', Array)
#12 /var/www/html/vendor/craftcms/cms/src/console/ControllerTrait.php(89): yii\console\Controller->runAction('', Array)
#13 /var/www/html/vendor/craftcms/cms/src/console/Controller.php(216): craft\console\Controller->traitRunAction('', Array)
#14 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): craft\console\Controller->runAction('', Array)
#15 /var/www/html/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('install', Array)
#16 /var/www/html/vendor/craftcms/cms/src/console/Application.php(91): yii\console\Application->runAction('install', Array)
#17 /var/www/html/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('install', Array)
#18 /var/www/html/vendor/craftcms/cms/src/console/Application.php(122): yii\console\Application->handleRequest(Object(craft\console\Request))
#19 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): craft\console\Application->handleRequest(Object(craft\console\Request))
#20 /var/www/html/craft(22): yii\base\Application->run()
#21 {main}
*** failed to install Craft: An error occurred while executing the "craft\migrations\Install migration: SQLSTATE[42000]: Syntax error or access violation: 1253 COLLATION 'utf8mb4_0900_ai_ci' is not valid for CHARACTER SET 'utf8mb3'
The SQL being executed was: CREATE TABLE `addresses` (
        `id` int(11) NOT NULL,
        `primaryOwnerId` int(11),
        `fieldId` int(11),
        `countryCode` varchar(255) NOT NULL,
        `administrativeArea` varchar(255),
        `locality` varchar(255),
        `dependentLocality` varchar(255),
        `postalCode` varchar(255),
        `sortingCode` varchar(255),
        `addressLine1` varchar(255),
        `addressLine2` varchar(255),
        `addressLine3` varchar(255),
        `organization` varchar(255),
        `organizationTaxId` varchar(255),
        `fullName` varchar(255),
        `firstName` varchar(255),
        `lastName` varchar(255),
        `latitude` varchar(255),
        `longitude` varchar(255),
        `dateCreated` datetime(0) NOT NULL,
        `dateUpdated` datetime(0) NOT NULL,
        PRIMARY KEY(`id`)
) ENGINE = InnoDb DEFAULT CHARACTER SET = utf8 DEFAULT COLLATE = utf8mb4_0900_ai_ci

Failed to run php craft install: exit status 1
```

And here is the complete error message when updating from a Craft 4 site...

```
*** applying m221101_115859_create_entries_authors_table
    > dropping {{%entries_authors}} if it exists ... done (time: 0.005s)
    > create table {{%entries_authors}} ...Exception: SQLSTATE[42000]: Syntax error or access violation: 1253 COLLATION 'utf8mb4_0900_ai_ci' is not valid for CHARACTER SET 'utf8mb3'
The SQL being executed was: CREATE TABLE `entries_authors` (
        `entryId` int(11) NOT NULL,
        `authorId` int(11) NOT NULL,
        `sortOrder` smallint(6) UNSIGNED NOT NULL,
        PRIMARY KEY(`entryId`, `authorId`)
) ENGINE = InnoDb DEFAULT CHARACTER SET = utf8 DEFAULT COLLATE = utf8mb4_0900_ai_ci (/var/www/html/vendor/yiisoft/yii2/db/Schema.php:676)
#0 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1307): yii\db\Schema->convertException(Object(PDOException), 'CREATE TABLE `e...')
#1 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1102): yii\db\Command->internalExecute('CREATE TABLE `e...')
#2 /var/www/html/vendor/yiisoft/yii2/db/Migration.php(322): yii\db\Command->execute()
#3 /var/www/html/vendor/craftcms/cms/src/migrations/m221101_115859_create_entries_authors_table.php(20): yii\db\Migration->createTable('{{%entries_auth...', Array)
#4 /var/www/html/vendor/craftcms/cms/src/db/Migration.php(49): craft\migrations\m221101_115859_create_entries_authors_table->safeUp()
#5 /var/www/html/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(758): craft\db\Migration->up()
#6 /var/www/html/vendor/craftcms/cms/src/console/controllers/MigrateController.php(365): yii\console\controllers\BaseMigrateController->migrateUp('m221101_115859_...')
#7 [internal function]: craft\console\controllers\MigrateController->actionAll()
#8 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#9 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#10 /var/www/html/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction('all', Array)
#11 /var/www/html/vendor/craftcms/cms/src/console/ControllerTrait.php(89): yii\console\Controller->runAction('all', Array)
#12 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): craft\console\controllers\MigrateController->runAction('all', Array)
#13 /var/www/html/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/all', Array)
#14 /var/www/html/vendor/craftcms/cms/src/console/Application.php(91): yii\console\Application->runAction('migrate/all', Array)
#15 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(212): craft\console\Application->runAction('migrate/all', Array)
#16 /var/www/html/vendor/craftcms/cms/src/console/Controller.php(207): yii\base\Controller->run('migrate/all', Array)
#17 /var/www/html/vendor/craftcms/cms/src/console/controllers/UpController.php(60): craft\console\Controller->run('migrate/all', Array)
#18 [internal function]: craft\console\controllers\UpController->actionIndex()
#19 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#20 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#21 /var/www/html/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction('', Array)
#22 /var/www/html/vendor/craftcms/cms/src/console/ControllerTrait.php(89): yii\console\Controller->runAction('', Array)
#23 /var/www/html/vendor/craftcms/cms/src/console/Controller.php(216): craft\console\Controller->traitRunAction('', Array)
#24 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): craft\console\Controller->runAction('', Array)
#25 /var/www/html/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('up', Array)
#26 /var/www/html/vendor/craftcms/cms/src/console/Application.php(91): yii\console\Application->runAction('up', Array)
#27 /var/www/html/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('up', Array)
#28 /var/www/html/vendor/craftcms/cms/src/console/Application.php(122): yii\console\Application->handleRequest(Object(craft\console\Request))
#29 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): craft\console\Application->handleRequest(Object(craft\console\Request))
#30 /var/www/html/craft(22): yii\base\Application->run()
#31 {main}
*** failed to apply m221101_115859_create_entries_authors_table (time: 0.018s)


0 from 22 migrations were applied.

Migration failed. The rest of the migrations are canceled.

Restore a database backup before trying again.

Aborting remaining tasks.
Failed to run php craft up: exit status 1

```

Hope that helps, let me know if you need anything else!

**Comment by brandonkelly** [comment]
@lindseydiloreto and I got to the bottom of this today. It’s reproducible when the `driver` isn’t explicitly set by `.env` (`CRAFT_DB_DRIVER`) or `config/db.php`, and so it gets set to `mysql` by default – but only after Craft would have normalize the `charset` from `utf8` to `utf8mb4`.

Fixed for the next release!

**Comment by brandonkelly** [comment]
Craft 5.0.0-beta.4 is out with that fix 🎉

**Comment by kmgdevelopment** [comment]
Just wanted to chime in that I just got this error today so maybe not quite fixed after all? Explicitly setting 

```
CRAFT_DB_CHARSET=utf8mb4
CRAFT_DB_COLLATION=utf8mb4_unicode_ci
```

in the `.env` file as Lindsey suggested fixed the issue. Here's what my `db` config file looks like:

```
return [
    'dsn' => getenv('DB_DSN'),
    'user' => getenv('DB_USER'),
    'password' => getenv('DB_PASSWORD'),
    'schema' => getenv('DB_SCHEMA'),
    'tablePrefix' => getenv('DB_TABLE_PREFIX'),
];
```

And my database settings in `.env` (running locally on ddev):

```
DB_DSN="mysql:host=db;port=3306;dbname=db;"
DB_DRIVER="mysql"
DB_SERVER="db"
DB_PORT="3306"
DB_DATABASE="db"
DB_USER="db"
DB_PASSWORD="db"
DB_SCHEMA="public"
DB_TABLE_PREFIX=""
```
