### ISSUE TITLE
[5.x]: voku/stringy not compatible with PHP 8.4

### ISSUE THREAD

**Issue by jordikroon** [craftcms/cms#16606]
### Description

The package Voku/stringy is not compatible with PHP 8.4. This package uses by Craft CMS within composer.json seems to be abandoned as has not received any updates nor for 2 years. Or longer if you consider major patches.

Since PHP 8.4 all nullable parameters without a question mark (`string $test = null`) are deprecated and should be prefixed with `?`.

The console gives a lot of deprecations. This even occurs on commands like `craft up`. While there are methods to suppress, ideally the deprecations are resolved.

```log
PHP Deprecated:  voku\helper\UTF8::extract_text(): Implicitly marking parameter $length as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/portable-utf8/src/voku/helper/UTF8.php on line 1622

PHP Deprecated:  voku\helper\UTF8::file_get_contents(): Implicitly marking parameter $offset as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/portable-utf8/src/voku/helper/UTF8.php on line 1842

PHP Deprecated:  voku\helper\UTF8::file_get_contents(): Implicitly marking parameter $max_length as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/portable-utf8/src/voku/helper/UTF8.php on line 1842

PHP Deprecated:  voku\helper\UTF8::getSupportInfo(): Implicitly marking parameter $key as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/portable-utf8/src/voku/helper/UTF8.php on line 2580

PHP Deprecated:  Stringy\Stringy::__construct(): Implicitly marking parameter $encoding as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/stringy/src/Stringy.php on line 77

Deprecated: Stringy\Stringy::create(): Implicitly marking parameter $encoding as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/stringy/src/Stringy.php on line 957

Deprecated:  Stringy\Stringy::extractText(): Implicitly marking parameter $length as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/stringy/src/Stringy.php on line 1324
```

### Craft CMS version

5.6.4

### PHP version

8.4

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
We’re aware of that, but decided to hold off on addressing it for a while, to see if the project ends up getting picked back up, or if a strong fork/alternative library emerges. Our only other option would be to fork it ourselves, but we’re not currently qualified to maintain it (beyond keeping it up-to-date with PHP changes), so that would only be a last resort.

**Comment by brandonkelly** [comment]
Craft does attempt to hide deprecation errors, so I’m not sure why they would be shown in your CLI output:

https://github.com/craftcms/cms/blob/7547163b18b33b3ccde54ea97713a95fd2e94f14/bootstrap/bootstrap.php#L159-L160

**Comment by terryupton** [comment]
Hey @brandonkelly 
I have also come up against this issue as I started a new project on 8.4 and also updated a project for a new server migration (upgrade). Whilst these are only warnings; would be be best to stick to 8.3 for now? 

Do you have any further updates or new plans to resolve this?

**Comment by brandonkelly** [comment]
I wouldn’t consider it a reason to stick with PHP 8.3, but it’s up to you.

Since Stringy seems to be abandonware, we’ll consider our other options for Craft 6.

**Comment by maxfenton** [comment]
This is the bulk of the error using DDEV with PHP 8.4

Maybe the deprecation warning comes back only when Blitz is enabled?

```
An Error occurred while handling another error:
yii\web\HeadersAlreadySentException: Headers already sent in /var/www/html/vendor/voku/portable-utf8/src/voku/helper/UTF8.php on line 8704. in /var/www/html/vendor/yiisoft/yii2/web/Response.php:369
Stack trace:
#0 /var/www/html/vendor/yiisoft/yii2/web/Response.php(342): yii\web\Response->sendHeaders()
#1 /var/www/html/vendor/yiisoft/yii2/web/ErrorHandler.php(136): yii\web\Response->send()
#2 /var/www/html/vendor/craftcms/cms/src/web/ErrorHandler.php(226): yii\web\ErrorHandler->renderException()
#3 /var/www/html/vendor/yiisoft/yii2/base/ErrorHandler.php(152): craft\web\ErrorHandler->renderException()
#4 /var/www/html/vendor/craftcms/cms/src/web/ErrorHandler.php(102): yii\base\ErrorHandler->handleException()
#5 [internal function]: craft\web\ErrorHandler->handleException()
#6 {main}
Previous exception:
yii\base\ErrorException: session_name(): Session name cannot be changed after headers have already been sent in /var/www/html/vendor/yiisoft/yii2/web/Session.php:348
Stack trace:
#0 /var/www/html/vendor/craftcms/cms/src/web/ErrorHandler.php(115): yii\base\ErrorHandler->handleError()
#1 [internal function]: craft\web\ErrorHandler->handleError()
#2 /var/www/html/vendor/yiisoft/yii2/web/Session.php(348): session_name()
#3 /var/www/html/vendor/yiisoft/yii2/base/Component.php(180): yii\web\Session->setName()
#4 /var/www/html/vendor/yiisoft/yii2/BaseYii.php(557): yii\base\Component->__set()
#5 /var/www/html/vendor/yiisoft/yii2/base/BaseObject.php(107): yii\BaseYii::configure()
#6 [internal function]: yii\base\BaseObject->__construct()
#7 /var/www/html/vendor/yiisoft/yii2/di/Container.php(419): ReflectionClass->newInstanceArgs()
#8 /var/www/html/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build()
#9 /var/www/html/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get()
#10 /var/www/html/vendor/craftcms/cms/src/Craft.php(71): yii\BaseYii::createObject()
#11 /var/www/html/vendor/craftcms/cms/src/config/app.web.php(30): Craft::createObject()
#12 [internal function]: {closure:/var/www/html/vendor/craftcms/cms/src/config/app.web.php:28}()
#13 /var/www/html/vendor/yiisoft/yii2/di/Container.php(633): call_user_func_array()
#14 /var/www/html/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->invoke()
#15 /var/www/html/vendor/yiisoft/yii2/di/ServiceLocator.php(137): yii\BaseYii::createObject()
#16 /var/www/html/vendor/yiisoft/yii2/base/Module.php(766): yii\di\ServiceLocator->get()
#17 /var/www/html/vendor/craftcms/cms/src/web/Application.php(380): yii\base\Module->get()
#18 /var/www/html/vendor/yiisoft/yii2/web/Application.php(178): craft\web\Application->get()
#19 /var/www/html/vendor/craftcms/cms/src/helpers/Session.php(112): yii\web\Application->getSession()
#20 /var/www/html/vendor/craftcms/cms/src/helpers/Session.php(133): craft\helpers\Session::session()
#21 /var/www/html/vendor/craftcms/cms/src/helpers/Session.php(92): craft\helpers\Session::exists()
#22 /var/www/html/vendor/craftcms/cms/src/web/User.php(536): craft\helpers\Session::has()
#23 /var/www/html/vendor/yiisoft/yii2/web/User.php(199): craft\web\User->renewAuthStatus()
#24 /var/www/html/vendor/putyourlightson/craft-blitz/src/services/CacheRequestService.php(135): yii\web\User->getIdentity()
#25 /var/www/html/vendor/putyourlightson/craft-blitz/src/Blitz.php(314): putyourlightson\blitz\services\CacheRequestService->getIsCacheableRequest()
#26 [internal function]: putyourlightson\blitz\Blitz->{closure:putyourlightson\blitz\Blitz::registerCacheableRequestEvents():311}()
#27 /var/www/html/vendor/yiisoft/yii2/base/Event.php(312): call_user_func()
#28 /var/www/html/vendor/yiisoft/yii2/base/Component.php(654): yii\base\Event::trigger()
#29 /var/www/html/vendor/craftcms/cms/src/base/ApplicationTrait.php(547): yii\base\Component->trigger()
#30 /var/www/html/vendor/craftcms/cms/src/base/ApplicationTrait.php(1633): craft\web\Application->trigger()
#31 /var/www/html/vendor/craftcms/cms/src/web/Application.php(110): craft\web\Application->_postInit()
#32 /var/www/html/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\web\Application->init()
#33 /var/www/html/vendor/yiisoft/yii2/base/Application.php(204): yii\base\BaseObject->__construct()
#34 [internal function]: yii\base\Application->__construct()
#35 /var/www/html/vendor/yiisoft/yii2/di/Container.php(419): ReflectionClass->newInstanceArgs()
#36 /var/www/html/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build()
#37 /var/www/html/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get()
#38 /var/www/html/vendor/craftcms/cms/src/Craft.php(71): yii\BaseYii::createObject()
#39 /var/www/html/vendor/craftcms/cms/bootstrap/bootstrap.php(349): Craft::createObject()
#40 /var/www/html/vendor/craftcms/cms/bootstrap/web.php(40): require('...')
#41 /var/www/html/web/index.php(11): require('...')
#42 {main}
```

---

`composer.json`
```
{
  "name": "projectname",
  "minimum-stability": "dev",
  "prefer-stable": true,
  "require": {
    "craftcms/aws-s3": "2.2.2",
    "craftcms/ckeditor": "4.8.0",
    "craftcms/cms": "5.7.6",
    "mmikkel/cp-field-inspect": "2.0.4",
    "mmikkel/retcon": "3.2.1",
    "nystudio107/craft-emptycoalesce": "5.0.0",
    "nystudio107/craft-retour": "5.0.10",
    "nystudio107/craft-seomatic": "5.1.13",
    "nystudio107/craft-vite": "5.0.1",
    "putyourlightson/craft-blitz": "5.10.5",
    "spacecatninja/imager-x": "5.1.3",
    "spacecatninja/imager-x-aws-serverless-transformer": "3.0.2",
    "spacecatninja/imager-x-power-pack": "1.0.5",
    "spicyweb/craft-embedded-assets": "5.4.3",
    "vandres/craft-matrix-extended": "v4.2.1",
    "verbb/expanded-singles": "3.0.2",
    "verbb/navigation": "3.0.8",
    "viget/craft-classnames": "3.0.0",
    "viget/craft-viget-base": "^6.0",
    "vlucas/phpdotenv": "^5.4.0"
  },
  "require-dev": {
    "craftcms/ecs": "dev-main",
    "craftcms/generator": "^2.0.0",
    "craftcms/phpstan": "dev-main",
    "nystudio107/craft-autocomplete": "^1.12",
    "yiisoft/yii2-shell": "^2.0.3"
  },
  "autoload": {
    "psr-4": {
      "modules\\": "modules/"
    }
  },
  "config": {
    "allow-plugins": {
      "craftcms/plugin-installer": true,
      "yiisoft/yii2-composer": true
    },
    "sort-packages": true,
    "optimize-autoloader": true,
    "platform": {
      "php": "8.4"
    }
  },
  "scripts": {
    "ecs-check": "ecs check --ansi",
    "ecs-fix": "ecs check --ansi --fix",
    "phpstan": "phpstan --memory-limit=1G"
  },
  "repositories": [
    {
      "type": "composer",
      "url": "https://composer.craftcms.com",
      "canonical": false
    }
  ]
}
```

**Comment by joshuapease** [comment]
It looks like there has been some progress on this in the voku/portable-utf8 repo. 

Although I don't think a release has happened yet. 

https://github.com/voku/portable-utf8/pull/208#issuecomment-2898560715

**Comment by jan-dh** [comment]
@brandonkelly seeing how the last tag was in March 2023, I'm not sure if it makes much sense in waiting around for a tag: https://github.com/voku/portable-utf8/tags

**Comment by Antimated** [comment]
@brandonkelly Not sure if you are aware but if you try to update plugins via the CMS the screen will just be stuck on `checking server requirements`. The only fix was to downgrade to php 8.3.

<img width="924" height="480" alt="Image" src="https://github.com/user-attachments/assets/f05c621c-f5cc-4f17-9098-6b392aef6792" />

**Comment by koenvdp** [comment]
We resolved this in our PHP 8.4 projects by just adding the error reporting line from Craft's bootstrap.php to our own projects bootstrap.php file. (the one copied from the starter project: [https://github.com/craftcms/craft/blob/5.x/bootstrap.php](url))

`$errorLevel = E_ALL & ~E_DEPRECATED & ~E_USER_DEPRECATED;`
`error_reporting($errorLevel);`

I assume the deprecated errors are triggered when the Voku/stringy package is autoloaded, which could be before Craft's bootstrap.php file is called. So making sure no deprecated errors are reported before loading Composer's autoloader should fix this.

**Comment by boboldehampsink** [comment]
@brandonkelly any chance of getting the fix in? We're still stuck on 8.3 because of this, and it is being deprecated soon.

**Comment by brandonkelly** [comment]
@boboldehampsink Craft already hides `E_DEPRECATED` from its bootstrap file:

https://github.com/craftcms/cms/blob/ff394ccb9e70c83f16f47ea159ab2331b5e05084/bootstrap/bootstrap.php#L159-L160

**Comment by boboldehampsink** [comment]
@brandonkelly just tried to boot a project with PHP 8.4 (latest Craft 4 in this case) but still seeing errors. Dev Mode is on. Any idea on where to look?

**Comment by boboldehampsink** [comment]
@brandonkelly those deprecation logs are being triggered before Craft’s bootstrap runs (because composer's autoloader is loaded first), so Craft’s “ignore E_USER_DEPRECATED” setting never gets a chance to mute them

**Comment by brandonkelly** [comment]
@boboldehampsink Ah, in that case I guess you’d need to add an `error_reporting()` call in your project’s `bootstrap.php` file, then, before the autoloader gets loaded.

**Comment by boboldehampsink** [comment]
@brandonkelly yeah well in any case this means I ignore all deprecation warnings, also of other and my own code. I would prefer you guys use a php 8.4 compatible fork of this project as part of the package?

**Comment by brandonkelly** [comment]
Just made that change to the `craftcms/craft` starter: https://github.com/craftcms/craft/commit/e31038d7cbe7a03e1c35c15883bd0248f4306c8d

**Comment by brandonkelly** [comment]
> I would prefer you guys use a php 8.4 compatible fork of this project as part of the package?

Me too, do you know of one?

**Comment by boboldehampsink** [comment]
@brandonkelly as far as I can tell, its already on their master branch. Shouldn't be too hard to lock that commit into Craft instead of the older, tagged release right?

Or just fork that to the Craft CMS org and tag it- it wouldn't even need changes

**Comment by jordikroon** [comment]
@brandonkelly Could we have an update regarding this? There seems to be no activity from Stringy within the package. Thus not really maintained.

We find ourself in the situation where disable all deprecations is not viable, especially since Craft 6 is coming up with Laravel. We want to have our systems ready for that by ensuring all possible deprecation are fixed.

Additionally, we are already at PHP 8.5 and 8.3 support will officially be dropped in 20 days (Dec 31 2025).
Would it be possible to have a fork with the PHP 8.4 patch (or even use composer patches)?

**Comment by brandonkelly** [comment]
You can update to https://github.com/voku/portable-utf8/commit/d41ec586facb9c76a8c5c92515b78532a24148a3 (the commit that fixed the deprecation errors) in your project by running the following command:

```sh
composer require voku/portable-utf8:"dev-master#d41ec586facb9c76a8c5c92515b78532a24148a3 as 6.0.13"
```

**Comment by geertvansoest** [comment]
@brandonkelly We tried the solution you suggest, but this doesn't seem to work in our DDEV environment. Running `craft up` afterwards still occurs several deprecation warnings related to `voku/portable-utf8` and `voku/stringy`:

```console
PHP Deprecated:  voku\helper\UTF8::extract_text(): Implicitly marking parameter $length as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/portable-utf8/src/voku/helper/UTF8.php on line 1593

Deprecated: voku\helper\UTF8::extract_text(): Implicitly marking parameter $length as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/portable-utf8/src/voku/helper/UTF8.php on line 1593
PHP Deprecated:  voku\helper\UTF8::file_get_contents(): Implicitly marking parameter $offset as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/portable-utf8/src/voku/helper/UTF8.php on line 1815

Deprecated: voku\helper\UTF8::file_get_contents(): Implicitly marking parameter $offset as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/portable-utf8/src/voku/helper/UTF8.php on line 1815
PHP Deprecated:  voku\helper\UTF8::file_get_contents(): Implicitly marking parameter $max_length as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/portable-utf8/src/voku/helper/UTF8.php on line 1815

Deprecated: voku\helper\UTF8::file_get_contents(): Implicitly marking parameter $max_length as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/portable-utf8/src/voku/helper/UTF8.php on line 1815
PHP Deprecated:  voku\helper\UTF8::getSupportInfo(): Implicitly marking parameter $key as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/portable-utf8/src/voku/helper/UTF8.php on line 2531

Deprecated: voku\helper\UTF8::getSupportInfo(): Implicitly marking parameter $key as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/portable-utf8/src/voku/helper/UTF8.php on line 2531
PHP Deprecated:  voku\helper\UTF8::html_decode(): Implicitly marking parameter $flags as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/portable-utf8/src/voku/helper/UTF8.php on line 2863

Deprecated: voku\helper\UTF8::html_decode(): Implicitly marking parameter $flags as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/portable-utf8/src/voku/helper/UTF8.php on line 2863
PHP Deprecated:  voku\helper\UTF8::html_entity_decode(): Implicitly marking parameter $flags as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/portable-utf8/src/voku/helper/UTF8.php on line 3017

Deprecated: voku\helper\UTF8::html_entity_decode(): Implicitly marking parameter $flags as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/portable-utf8/src/voku/helper/UTF8.php on line 3017
PHP Deprecated:  voku\helper\UTF8::lcfirst(): Implicitly marking parameter $lang as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/portable-utf8/src/voku/helper/UTF8.php on line 4467

Deprecated: voku\helper\UTF8::lcfirst(): Implicitly marking parameter $lang as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/portable-utf8/src/voku/helper/UTF8.php on line 4467
PHP Deprecated:  voku\helper\UTF8::lcword(): Implicitly marking parameter $lang as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/portable-utf8/src/voku/helper/UTF8.php on line 4529

Deprecated: voku\helper\UTF8::lcword(): Implicitly marking parameter $lang as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/portable-utf8/src/voku/helper/UTF8.php on line 4529
PHP Deprecated:  voku\helper\UTF8::lcwords(): Implicitly marking parameter $lang as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/portable-utf8/src/voku/helper/UTF8.php on line 4563

Deprecated: voku\helper\UTF8::lcwords(): Implicitly marking parameter $lang as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/portable-utf8/src/voku/helper/UTF8.php on line 4563
PHP Deprecated:  voku\helper\UTF8::lowerCaseFirst(): Implicitly marking parameter $lang as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/portable-utf8/src/voku/helper/UTF8.php on line 4615

Deprecated: voku\helper\UTF8::lowerCaseFirst(): Implicitly marking parameter $lang as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/portable-utf8/src/voku/helper/UTF8.php on line 4615
PHP Deprecated:  voku\helper\UTF8::ltrim(): Implicitly marking parameter $chars as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/portable-utf8/src/voku/helper/UTF8.php on line 4643

Deprecated: voku\helper\UTF8::ltrim(): Implicitly marking parameter $chars as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/portable-utf8/src/voku/helper/UTF8.php on line 4643
PHP Deprecated:  voku\helper\UTF8::rtrim(): Implicitly marking parameter $chars as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/portable-utf8/src/voku/helper/UTF8.php on line 5721

Deprecated: voku\helper\UTF8::rtrim(): Implicitly marking parameter $chars as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/portable-utf8/src/voku/helper/UTF8.php on line 5721
PHP Deprecated:  voku\helper\UTF8::str_camelize(): Implicitly marking parameter $lang as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/portable-utf8/src/voku/helper/UTF8.php on line 5891

Deprecated: voku\helper\UTF8::str_camelize(): Implicitly marking parameter $lang as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/portable-utf8/src/voku/helper/UTF8.php on line 5891
PHP Deprecated:  voku\helper\UTF8::str_delimit(): Implicitly marking parameter $lang as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/portable-utf8/src/voku/helper/UTF8.php on line 6142

Deprecated: voku\helper\UTF8::str_delimit(): Implicitly marking parameter $lang as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/portable-utf8/src/voku/helper/UTF8.php on line 6142
PHP Deprecated:  voku\helper\UTF8::str_replace(): Implicitly marking parameter $count as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/portable-utf8/src/voku/helper/UTF8.php on line 7913

Deprecated: voku\helper\UTF8::str_replace(): Implicitly marking parameter $count as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/portable-utf8/src/voku/helper/UTF8.php on line 7913
PHP Deprecated:  voku\helper\UTF8::str_slice(): Implicitly marking parameter $end as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/portable-utf8/src/voku/helper/UTF8.php on line 8146

Deprecated: voku\helper\UTF8::str_slice(): Implicitly marking parameter $end as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/portable-utf8/src/voku/helper/UTF8.php on line 8146
PHP Deprecated:  voku\helper\UTF8::str_titleize(): Implicitly marking parameter $ignore as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/portable-utf8/src/voku/helper/UTF8.php on line 8927

Deprecated: voku\helper\UTF8::str_titleize(): Implicitly marking parameter $ignore as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/portable-utf8/src/voku/helper/UTF8.php on line 8927
PHP Deprecated:  voku\helper\UTF8::str_titleize(): Implicitly marking parameter $lang as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/portable-utf8/src/voku/helper/UTF8.php on line 8927

Deprecated: voku\helper\UTF8::str_titleize(): Implicitly marking parameter $lang as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/portable-utf8/src/voku/helper/UTF8.php on line 8927
PHP Deprecated:  voku\helper\UTF8::str_titleize(): Implicitly marking parameter $word_define_chars as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/portable-utf8/src/voku/helper/UTF8.php on line 8927

Deprecated: voku\helper\UTF8::str_titleize(): Implicitly marking parameter $word_define_chars as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/portable-utf8/src/voku/helper/UTF8.php on line 8927
PHP Deprecated:  voku\helper\UTF8::str_to_lines(): Implicitly marking parameter $remove_short_values as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/portable-utf8/src/voku/helper/UTF8.php on line 9290

Deprecated: voku\helper\UTF8::str_to_lines(): Implicitly marking parameter $remove_short_values as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/portable-utf8/src/voku/helper/UTF8.php on line 9290
PHP Deprecated:  voku\helper\UTF8::str_to_words(): Implicitly marking parameter $remove_short_values as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/portable-utf8/src/voku/helper/UTF8.php on line 9336

Deprecated: voku\helper\UTF8::str_to_words(): Implicitly marking parameter $remove_short_values as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/portable-utf8/src/voku/helper/UTF8.php on line 9336
PHP Deprecated:  voku\helper\UTF8::str_upper_camelize(): Implicitly marking parameter $lang as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/portable-utf8/src/voku/helper/UTF8.php on line 9600

Deprecated: voku\helper\UTF8::str_upper_camelize(): Implicitly marking parameter $lang as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/portable-utf8/src/voku/helper/UTF8.php on line 9600
PHP Deprecated:  voku\helper\UTF8::str_upper_first(): Implicitly marking parameter $lang as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/portable-utf8/src/voku/helper/UTF8.php on line 9626

Deprecated: voku\helper\UTF8::str_upper_first(): Implicitly marking parameter $lang as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/portable-utf8/src/voku/helper/UTF8.php on line 9626
PHP Deprecated:  voku\helper\UTF8::strcspn(): Implicitly marking parameter $length as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/portable-utf8/src/voku/helper/UTF8.php on line 9815

Deprecated: voku\helper\UTF8::strcspn(): Implicitly marking parameter $length as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/portable-utf8/src/voku/helper/UTF8.php on line 9815
PHP Deprecated:  voku\helper\UTF8::strip_tags(): Implicitly marking parameter $allowable_tags as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/portable-utf8/src/voku/helper/UTF8.php on line 9984

Deprecated: voku\helper\UTF8::strip_tags(): Implicitly marking parameter $allowable_tags as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/portable-utf8/src/voku/helper/UTF8.php on line 9984
PHP Deprecated:  voku\helper\UTF8::strspn(): Implicitly marking parameter $length as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/portable-utf8/src/voku/helper/UTF8.php on line 11437

Deprecated: voku\helper\UTF8::strspn(): Implicitly marking parameter $length as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/portable-utf8/src/voku/helper/UTF8.php on line 11437
PHP Deprecated:  voku\helper\UTF8::strtocasefold(): Implicitly marking parameter $lang as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/portable-utf8/src/voku/helper/UTF8.php on line 11667

Deprecated: voku\helper\UTF8::strtocasefold(): Implicitly marking parameter $lang as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/portable-utf8/src/voku/helper/UTF8.php on line 11667
PHP Deprecated:  voku\helper\UTF8::strtolower(): Implicitly marking parameter $lang as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/portable-utf8/src/voku/helper/UTF8.php on line 11722

Deprecated: voku\helper\UTF8::strtolower(): Implicitly marking parameter $lang as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/portable-utf8/src/voku/helper/UTF8.php on line 11722
PHP Deprecated:  voku\helper\UTF8::strtoupper(): Implicitly marking parameter $lang as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/portable-utf8/src/voku/helper/UTF8.php on line 11804

Deprecated: voku\helper\UTF8::strtoupper(): Implicitly marking parameter $lang as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/portable-utf8/src/voku/helper/UTF8.php on line 11804
PHP Deprecated:  voku\helper\UTF8::substr(): Implicitly marking parameter $length as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/portable-utf8/src/voku/helper/UTF8.php on line 12014

Deprecated: voku\helper\UTF8::substr(): Implicitly marking parameter $length as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/portable-utf8/src/voku/helper/UTF8.php on line 12014
PHP Deprecated:  voku\helper\UTF8::substr_compare(): Implicitly marking parameter $length as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/portable-utf8/src/voku/helper/UTF8.php on line 12181

Deprecated: voku\helper\UTF8::substr_compare(): Implicitly marking parameter $length as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/portable-utf8/src/voku/helper/UTF8.php on line 12181
PHP Deprecated:  voku\helper\UTF8::substr_count(): Implicitly marking parameter $length as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/portable-utf8/src/voku/helper/UTF8.php on line 12239

Deprecated: voku\helper\UTF8::substr_count(): Implicitly marking parameter $length as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/portable-utf8/src/voku/helper/UTF8.php on line 12239
PHP Deprecated:  voku\helper\UTF8::substr_count_in_byte(): Implicitly marking parameter $length as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/portable-utf8/src/voku/helper/UTF8.php on line 12339

Deprecated: voku\helper\UTF8::substr_count_in_byte(): Implicitly marking parameter $length as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/portable-utf8/src/voku/helper/UTF8.php on line 12339
PHP Deprecated:  voku\helper\UTF8::substr_in_byte(): Implicitly marking parameter $length as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/portable-utf8/src/voku/helper/UTF8.php on line 12491

Deprecated: voku\helper\UTF8::substr_in_byte(): Implicitly marking parameter $length as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/portable-utf8/src/voku/helper/UTF8.php on line 12491
PHP Deprecated:  voku\helper\UTF8::titlecase(): Implicitly marking parameter $lang as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/portable-utf8/src/voku/helper/UTF8.php on line 12882

Deprecated: voku\helper\UTF8::titlecase(): Implicitly marking parameter $lang as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/portable-utf8/src/voku/helper/UTF8.php on line 12882
PHP Deprecated:  voku\helper\UTF8::trim(): Implicitly marking parameter $chars as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/portable-utf8/src/voku/helper/UTF8.php on line 13388

Deprecated: voku\helper\UTF8::trim(): Implicitly marking parameter $chars as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/portable-utf8/src/voku/helper/UTF8.php on line 13388
PHP Deprecated:  voku\helper\UTF8::ucfirst(): Implicitly marking parameter $lang as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/portable-utf8/src/voku/helper/UTF8.php on line 13435

Deprecated: voku\helper\UTF8::ucfirst(): Implicitly marking parameter $lang as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/portable-utf8/src/voku/helper/UTF8.php on line 13435
PHP Deprecated:  voku\helper\UTF8::wordwrap_per_line(): Implicitly marking parameter $delimiter as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/portable-utf8/src/voku/helper/UTF8.php on line 14176

Deprecated: voku\helper\UTF8::wordwrap_per_line(): Implicitly marking parameter $delimiter as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/portable-utf8/src/voku/helper/UTF8.php on line 14176
PHP Deprecated:  voku\helper\UTF8::reduce_string_array(): Implicitly marking parameter $remove_short_values as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/portable-utf8/src/voku/helper/UTF8.php on line 14517

Deprecated: voku\helper\UTF8::reduce_string_array(): Implicitly marking parameter $remove_short_values as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/portable-utf8/src/voku/helper/UTF8.php on line 14517
PHP Deprecated:  Stringy\create(): Implicitly marking parameter $encoding as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/stringy/src/Create.php on line 17

Deprecated: Stringy\create(): Implicitly marking parameter $encoding as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/stringy/src/Create.php on line 17
PHP Deprecated:  Stringy\Stringy::__construct(): Implicitly marking parameter $encoding as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/stringy/src/Stringy.php on line 77
Deprecated: Stringy\Stringy::__construct(): Implicitly marking parameter $encoding as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/stringy/src/Stringy.php on line 77
PHP Deprecated:  Stringy\Stringy::between(): Implicitly marking parameter $offset as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/stringy/src/Stringy.php on line 601
Deprecated: Stringy\Stringy::between(): Implicitly marking parameter $offset as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/stringy/src/Stringy.php on line 601
PHP Deprecated:  Stringy\Stringy::create(): Implicitly marking parameter $encoding as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/stringy/src/Stringy.php on line 957
Deprecated: Stringy\Stringy::create(): Implicitly marking parameter $encoding as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/stringy/src/Stringy.php on line 957
PHP Deprecated:  Stringy\Stringy::extractText(): Implicitly marking parameter $length as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/stringy/src/Stringy.php on line 1324
Deprecated: Stringy\Stringy::extractText(): Implicitly marking parameter $length as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/stringy/src/Stringy.php on line 1324
PHP Deprecated:  Stringy\Stringy::lineWrap(): Implicitly marking parameter $delimiter as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/stringy/src/Stringy.php on line 2652
Deprecated: Stringy\Stringy::lineWrap(): Implicitly marking parameter $delimiter as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/stringy/src/Stringy.php on line 2652
PHP Deprecated:  Stringy\Stringy::lineWrapAfterWord(): Implicitly marking parameter $delimiter as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/stringy/src/Stringy.php on line 2691
Deprecated: Stringy\Stringy::lineWrapAfterWord(): Implicitly marking parameter $delimiter as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/stringy/src/Stringy.php on line 2691
PHP Deprecated:  Stringy\Stringy::slice(): Implicitly marking parameter $end as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/stringy/src/Stringy.php on line 3825
Deprecated: Stringy\Stringy::slice(): Implicitly marking parameter $end as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/stringy/src/Stringy.php on line 3825
PHP Deprecated:  Stringy\Stringy::split(): Implicitly marking parameter $limit as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/stringy/src/Stringy.php on line 3966
Deprecated: Stringy\Stringy::split(): Implicitly marking parameter $limit as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/stringy/src/Stringy.php on line 3966
PHP Deprecated:  Stringy\Stringy::splitCollection(): Implicitly marking parameter $limit as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/stringy/src/Stringy.php on line 4007
Deprecated: Stringy\Stringy::splitCollection(): Implicitly marking parameter $limit as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/stringy/src/Stringy.php on line 4007
PHP Deprecated:  Stringy\Stringy::substr(): Implicitly marking parameter $length as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/stringy/src/Stringy.php on line 4188
Deprecated: Stringy\Stringy::substr(): Implicitly marking parameter $length as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/stringy/src/Stringy.php on line 4188
PHP Deprecated:  Stringy\Stringy::substring(): Implicitly marking parameter $length as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/stringy/src/Stringy.php on line 4216
Deprecated: Stringy\Stringy::substring(): Implicitly marking parameter $length as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/stringy/src/Stringy.php on line 4216
PHP Deprecated:  Stringy\Stringy::titleize(): Implicitly marking parameter $ignore as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/stringy/src/Stringy.php on line 4364
Deprecated: Stringy\Stringy::titleize(): Implicitly marking parameter $ignore as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/stringy/src/Stringy.php on line 4364
PHP Deprecated:  Stringy\Stringy::titleize(): Implicitly marking parameter $word_define_chars as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/stringy/src/Stringy.php on line 4364
Deprecated: Stringy\Stringy::titleize(): Implicitly marking parameter $word_define_chars as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/stringy/src/Stringy.php on line 4364
PHP Deprecated:  Stringy\Stringy::titleize(): Implicitly marking parameter $language as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/stringy/src/Stringy.php on line 4364
Deprecated: Stringy\Stringy::titleize(): Implicitly marking parameter $language as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/stringy/src/Stringy.php on line 4364
PHP Deprecated:  Stringy\Stringy::trim(): Implicitly marking parameter $chars as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/stringy/src/Stringy.php on line 4670
Deprecated: Stringy\Stringy::trim(): Implicitly marking parameter $chars as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/stringy/src/Stringy.php on line 4670
PHP Deprecated:  Stringy\Stringy::trimLeft(): Implicitly marking parameter $chars as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/stringy/src/Stringy.php on line 4694
Deprecated: Stringy\Stringy::trimLeft(): Implicitly marking parameter $chars as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/stringy/src/Stringy.php on line 4694
PHP Deprecated:  Stringy\Stringy::trimRight(): Implicitly marking parameter $chars as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/stringy/src/Stringy.php on line 4718
Deprecated: Stringy\Stringy::trimRight(): Implicitly marking parameter $chars as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/stringy/src/Stringy.php on line 4718
PHP Deprecated:  Stringy\Stringy::words(): Implicitly marking parameter $remove_short_values as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/stringy/src/Stringy.php on line 5013
Deprecated: Stringy\Stringy::words(): Implicitly marking parameter $remove_short_values as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/stringy/src/Stringy.php on line 5013
PHP Deprecated:  Stringy\Stringy::wordsCollection(): Implicitly marking parameter $remove_short_values as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/stringy/src/Stringy.php on line 5063
Deprecated: Stringy\Stringy::wordsCollection(): Implicitly marking parameter $remove_short_values as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/voku/stringy/src/Stringy.php on line 5063
Checking for pending Craft and plugin migrations ...
No new migrations found. Your system is up to date.
                                                                                                                                                                                                                                                                                                                            
Checking for pending content migrations ...
No new migrations found. Your system is up-to-date.
                                                                                                                                                                                                                                                                                                                            
Updating license info ... done
```

**Comment by brandonkelly** [comment]
Spent the day updating `StringHelper` to work independently of Stringy (#18169). Will get this in for Craft 5.9.

**Comment by brandonkelly** [comment]
Craft 5.9.0 is out with that change 🎉

**Comment by terryupton** [comment]
> Craft 5.9.0 is out with that change 🎉

@brandonkelly any plans to port this back into Craft 4? So we can update those to PHP 8.5?

**Comment by brandonkelly** [comment]
@terryupton No, Craft 4 is now technically [end of life](https://craftcms.com/knowledge-base/supported-versions).
