### ISSUE TITLE
[5.x]: Duplicated queries when reading entry type handle

### ISSUE THREAD

**Issue by zalito12** [craftcms/cms#18142]
### Description
If you have a nested matrix field accessing the entry type handle will create duplicated queries.

### Steps to reproduce

1. Create an entry type with a matrix field
2. Create another entry type with a matrix field that includes the previous one (one level of nested entries)
3. Create an entry with one nested entry.
4. Access the template of the entry and read the handle of the nested entry.
5. You will see duplicated queries even with the simplest template possible

### Expected behavior
No duplicated queries

### Actual behavior
You get duplicated queries when reading the entry type handle but not for other fields like the title.

### More information

Tested on a clean project with craft 5.8.21

My entries structure looks like this:

<img width="370" height="359" alt="Image" src="https://github.com/user-attachments/assets/b39ff60f-90c9-4013-817b-0bf6331bade8" />

<img width="362" height="355" alt="Image" src="https://github.com/user-attachments/assets/ed6cb24b-7014-4bf8-a242-7d4feb1b15f9" />

My template look like this:

````
<!DOCTYPE html>
<html lang="en-US">
  <body class="ltr">
    <main>
      {% set layouts = entry.taxonomyContent.with([['widgetList']]).all() %}
      {% for layout in layouts %}
        {# Othe code #}
        {% for widget in layout.widgetList.all() %}
          {{ widget.type.handle }}<br />
        {% endfor %}
      {% endfor %}
    </main>
  </body>
</html>
````

I see this duplicated queries on the debug toolbar:

<img width="1071" height="897" alt="Image" src="https://github.com/user-attachments/assets/b2d38a61-1e8d-4f5e-8695-812d97caab2b" />

### Craft CMS version

5.8.21

### PHP version

8.3.17

### Operating system and version

Linux 6.6.87.2-microsoft-standard-WSL2

### Database type and version

MySQL 8.0.40

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

Nothing, clean install

**Comment by brandonkelly** [comment]
Thanks for reporting that! I’ve fixed this for Craft 5.9. (https://github.com/craftcms/cms/commit/3caca08366644996e0d09edff44fdf7700f85c6b)

If you’d like to help test, you can update to the `5.9` branch by changing your `craftcms/cms` requirement in composer.json to:

```json
"craftcms/cms": "5.9.x-dev as 5.9.0-alpha",
```

Then run `composer update` + `craft up`.

Note that 5.9 includes new migrations, so it’s not possible to revert to 5.8 without restorting a database backup.

**Comment by zalito12** [comment]
Thank you! I will try it, I saw the commit, this will fix content blocks too, nice!

Edit: I updated my craft version and I don't see duplicated when you have just one entry, but when you have at least 2 parent entries with children the problem still arise.

**Comment by brandonkelly** [comment]
@zalito12 Doh, thanks for pointing that out. Fixed now.

**Comment by zalito12** [comment]
Omg! It works perfect now!! Thank you 🥳

**Comment by brandonkelly** [comment]
Craft 5.9.0 is out with that change 🎉
