### ISSUE TITLE
On Update — "Allowed memory size of X bytes exhausted"

### ISSUE THREAD

**Issue by bryantwells** [craftcms/cms#1852]
### Description

I am unable to update Craft via the admin tool on a local MAMP server. The CMS only has a couple placeholder entries made within the CMS and the element API is installed.

```
Status: Internal Server Error

Response: <pre>PHP Fatal Error &#039;yii\base\ErrorException&#039; with message &#039;Allowed memory size of 268435456 bytes exhausted (tried to allocate 110592 bytes)&#039; 

in /Users/bryantwells/Sites/verdes/verdes-api/vendor/composer/composer/src/Composer/Util/RemoteFilesystem.php:386

Stack trace:
#0 [internal function]: yii\base\ErrorHandler-&gt;handleFatalError()
#1 {main}</pre>
```

My PHP's memory_limit was set to 128M, upped to 256M and saw no change. 

### Steps to reproduce

1. Basic "update" command through the utilities panel

### Additional info

- Craft version: 3.0.0-beta.21
- PHP version: 7.0.8
- Database driver & version: MYSQL 5.5.42
- Plugins & versions: Element API 1.6.0

**Comment by takobell** [comment]
Was that the whole stack trace for the error?  If you don't mind sharing your `craft/storage/logs` files publicly, could you zip them up and attach them here?

**Comment by bryantwells** [comment]
Within the response, in dev mode, yes — that what the complete stack trace. Attaching logs below...

[logs.zip](https://github.com/craftcms/cms/files/1160025/logs.zip)

**Comment by brandonkelly** [comment]
Quick update – issue here is that Composer takes up a ton of time/memory when updating dependencies. We’re working on improving that in two ways: 1) the next Craft CMS update will stop relying on Composer (via http://asset-packagist.org) for installing Craft’s JS dependencies, which reduces Craft/Yii’s dependency count by 17

**Comment by brandonkelly** [comment]
We haven’t seen many problems with Composer memory usage ever since 3b88277f, so going to close this.

**Comment by zzseba78** [comment]
I´m on this problem now too, updating to latest version of Craft 3.
```
Estado: Internal Server Error

Respuesta: <pre>PHP Fatal Error &#039;yii\base\ErrorException&#039; with message &#039;Allowed memory size of 134217728 bytes exhausted (tried to allocate 17316216 bytes)&#039;

in /Applications/MAMP/htdocs/MarinePacific/vendor/composer/composer/src/Composer/Util/RemoteFilesystem.php:458

Stack trace:
#0 [internal function]: yii\base\ErrorHandler-&gt;handleFatalError()
#1 {main}</pre> 
```

**Comment by brandonkelly** [comment]
@jdsimcoe Do you have the [phpMaxMemoryLimit](https://docs.craftcms.com/v3/config/config-settings.html#phpmaxmemorylimit) setting set by chance?

**Comment by angrybrad** [comment]
@brandonkelly @jdsimcoe  `1610612736` is 1.6G or 1600M. Are you sure you're editing the correct php.ini file?

**Comment by jdsimcoe** [comment]
In the CP it shows my `memory_limit` as `512M`:

![image](https://user-images.githubusercontent.com/275617/67587904-a5cdb900-f709-11e9-8b7f-a6fc1f1d307a.png)

Since I'm running on Homebrew I've edited the `php.ini` file in `/usr/local/etc/php/7.3/php.ini`. In my `config/general.php` I have 'maxUploadFileSize'=> 268435456` but no `phpMaxMemoryLimit` set.

**Comment by brandonkelly** [comment]
PHP could be using a different `php.ini` file for the CLI. Try running this to find out:

```bash
php -i | grep 'Configuration File'
```

**Comment by jdsimcoe** [comment]
@brandonkelly It is only using the one:

```
Configuration File (php.ini) Path => /usr/local/etc/php/7.3
Loaded Configuration File => /usr/local/etc/php/7.3/php.ini
```

**Comment by angrybrad** [comment]
@jdsimcoe Fixed in https://github.com/craftcms/cms/commit/df40f585cef3d7e47f811f73b08d9d71bbc9c9b2 and will be included in the next 3.3.14 release.

**Comment by jdsimcoe** [comment]
This is great to hear! Thanks so much for bearing with me @angrybrad. Also thanks for not getting "angry".

P.S. pardon my super lame attempt at a pun.

**Comment by natebeaty** [comment]
This is great to hear! This has happened for me locally w/ same setup (7.3 via homebrew) for a while, causing it to sit for a loooong time after running `./craft update all` before barfing out that memory error, and requiring a `composer update` to finish up. Would love for that to stop happening.

**Comment by notasausage** [comment]
I'm still seeing this issue in Craft 3.3.18.4 when trying to install a plugin from the Plugin Store. I'm running a Craft 3 development site using MAMP Pro on macOS Mojave, with my php.ini allowing for a memory limit of 256MB (I've also tried 512 and 1024 to no avail). I'm trying to install the Imager (aelvan/imager) plugin and I'm getting the following error:

```
Status: Internal Server Error

Response: <pre>PHP Fatal Error &#039;yii\base\ErrorException&#039; with message &#039;Allowed memory size of 268435456 bytes exhausted (tried to allocate 20480 bytes)&#039;

in /Users/patrick/Development/tokenring.com/vendor/composer/composer/src/Composer/DependencyResolver/GenericRule.php:36

Stack trace:
#0 [internal function]: yii\base\ErrorHandler-&gt;handleFatalError()
#1 {main}</pre>
```
I was able to install composer and run `composer require aelvan/imager` from Terminal, and the installation was successful.

**Comment by brandonkelly** [comment]
Did you capture the errors after changing `memory_limit` to verify that the max bytes in those errors were not also `268435456` ?

**Comment by notasausage** [comment]
> Did you capture the errors after changing memory_limit to verify that the max bytes in those errors were not also 268435456 ?

Actually, if I remember correctly, the also said the same even after adjusting the limit a few times.

**Comment by brandonkelly** [comment]
If that’s the case, then either you didn’t edit the right php.ini file, or the PHP server wasn’t rebooted, which needs to happen before the changes will take effect.

**Comment by jsunsawyer** [comment]
I'm also getting this error when trying to update Craft through the backend.

```
Status: Internal Server Error

Response: <pre>PHP Fatal Error &#039;yii\base\ErrorException&#039; with message &#039;Allowed memory size of 268435456 bytes exhausted (tried to allocate 4096 bytes)&#039;

in /Users/jason/Sites/filmstreams/craft/vendor/composer/composer/src/Composer/DependencyResolver/RuleSetGenerator.php:126

Stack trace:
#0 [internal function]: yii\base\ErrorHandler-&gt;handleFatalError()
#1 {main}</pre>
```

This is happened when trying to upgrade from Craft 3.4.3 to 3.4.5.

My memory_limit in PHP Info is 256M

My composer file was updated to reflect the changes, so simply deleting the composer.lock file and running composer install in terminal got me up-to-date.

**Comment by jsunsawyer** [comment]
Ended up resolving this by reinstalling my entire valet setup.
