### ISSUE TITLE
Bug with post dates when saving an entry.

### ISSUE THREAD

**Issue by tyler-shaw** [craftcms/cms#2819]
### Description

First off, my website is set to Eastern Time (America/New_York). The time value for the Post Date is changing automatically whenever I save an entry. Let's say that I set the post time to 2pm and save. If I open that entry again, it displays as 2pm momentarily, before converting to UTC automatically on the client side. That means the time is now set to 6pm, and upon saving, the post time is changed.

There appears to be a script running that is changing this time to UTC despite initially loading as Eastern.

Here's a screenshot demonstrating that the actual value in the Post Date time field is different than the value in the HTML attribute: http://puu.sh/Ab13n/bf98e0d033.png

### Steps to reproduce

1. Set time zone to Eastern.
2. Create and save an entry.
3. Go to edit that entry, and notice that the time will automatically convert to UTC in the Post Date time input.

Note: I've reproduced this on multiple entry types, on completely different machines.

### Additional info

- Craft version: 3.0.3.1
- PHP version: Tested on two different installs, running 7.0.4 & 7.0.29
- Database driver & version: MySQL 5.5.5
- Plugins & versions: Redactor 1.1.0, Super Table 2.0.5

**Comment by tyler-shaw** [comment]
These seem to be the lines that do it: https://github.com/craftcms/cms/blob/develop/src/templates/_includes/forms/time.html#L30-L32

If I comment those out, then the page loads and the correct time is never overwritten with the time in UTC.

**Comment by brandonkelly** [comment]
We just fixed a similar bug (#2761) where the culprit ended up being a custom module that was initializing Twig before Craft had a chance to set itself to the system timezone, which resulted in Twig getting initialized with its timezone set to UTC.

Try changing your `craftcms/cms` version requirement in `composer.json` to `"dev-develop as 3.0.4"`, and then run `composer update`, and let me know if that fixes it for you.

**Comment by tyler-shaw** [comment]
Hi, thanks for getting back to me. I did as requested and that does appear to have fixed the issue. Thank you!

**Comment by brandonkelly** [comment]
Great, thanks for checking!

**Comment by thaoms** [comment]
I still have the issue when using the date picker field. I'm using UTC +2 CEST Europe/Brussels

Lets say the date picker field is 10:00, it shows in my template as 12:00 with the |date filter. ( .format() gives me the correct time, but I need the translation functionality of |date )

I have a related issue here that includes some screenshots.
https://github.com/solspace/craft3-calendar/issues/20

**Comment by brandonkelly** [comment]
@thaoms the fix hasn’t been formally released yet. Did you do these things?

> Try changing your `craftcms/cms` version requirement in `composer.json` to `"dev-develop as 3.0.4"`, and then run composer update, and let me know if that fixes it for you.
