### ISSUE TITLE
InvalidConfigException When updating from 3.1.14 to 3.1.16

### ISSUE THREAD

**Issue by tjdraper** [craftcms/cms#3965]
### Description

When updating from Craft 3.1.14 to 3.1.16, an exception is thrown

### Steps to reproduce

1. composer update
2. Try to run update migrations

### Additional info

- Craft version: 3.1.14
- PHP version: 7.2.8
- Database driver & version: MySQL 5.5.5 (That's what Craft Says, it's really MariaDB 10.3.12)

Error:

```
php craft migrate/all
Yii Migration Tool (based on Yii v2.0.16.1)

Migrated up successfully.
An Error occurred:
yii\base\InvalidConfigException: Unexpected data encountered in config data in /app/vendor/craftcms/cms/src/helpers/ProjectConfig.php:135
Stack trace:
#0 /app/vendor/craftcms/cms/src/helpers/ProjectConfig.php(139): craft\helpers\ProjectConfig::cleanupConfig(Array)
#1 /app/vendor/craftcms/cms/src/helpers/ProjectConfig.php(139): craft\helpers\ProjectConfig::cleanupConfig(Array)
#2 /app/vendor/craftcms/cms/src/helpers/ProjectConfig.php(139): craft\helpers\ProjectConfig::cleanupConfig(Array)
#3 /app/vendor/craftcms/cms/src/helpers/ProjectConfig.php(139): craft\helpers\ProjectConfig::cleanupConfig(Array)
#4 /app/vendor/craftcms/cms/src/helpers/ProjectConfig.php(139): craft\helpers\ProjectConfig::cleanupConfig(Array)
#5 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(604): craft\helpers\ProjectConfig::cleanupConfig(Array)
#6 [internal function]: craft\services\ProjectConfig->saveModifiedConfigData(Object(yii\base\Event))
#7 /app/vendor/yiisoft/yii2/base/Component.php(627): uopz_call_user_func(Array, Object(yii\base\Event))
#8 /app/vendor/yiisoft/yii2/base/Application.php(389): yii\base\Component->trigger('afterRequest')
#9 /app/CraftFrontController.php(33): yii\base\Application->run()
#10 /app/craft(3): require('/app/CraftFront...')
#11 {main}
```

**Comment by tjdraper** [comment]
I should note that for whatever reason I get all kinds of goofiness when trying to use project config so I have it completely disabled.

**Comment by brandonkelly** [comment]
That exception was put in place to combat a far worse issue with Sprout Fields, which I believe they fixed in v3.0.0-beta.45. Do you have that installed by chance?

**Comment by tjdraper** [comment]
Ahh. Yes, I do. So I should probably wait until 3.0.0 is released and then updating should go smoothly again?

**Comment by brandonkelly** [comment]
Start by reverting back to Craft 3.1.14. Easiest way to do that is from the terminal – go to your Craft project and run `./craft update craft 3.1.14`.

If that doesn’t work and you have Composer installed, change your `craftcms/cms` requirement to `3.1.14` manually in `composer.json`, and then run `composer update`.

Then make sure you’re able to access the Control Panel, and update Sprout Fields to v3.0.0-beta.45. Then try updating Craft to the latest again (now 3.1.17).

**Comment by tjdraper** [comment]
Sorry for delay, juggling a lot of balls.

I'm actually on 3.x of Sprout Fields. Current 3.2.8, which requires at least Craft 3.1.15. But I need the fix that just came out in 3.2.8 of Sprout Fields pretty badly.

I'm still getting the error about InvalidConfigException Unexpected Data, but it appears to happen after migrations and nothing seems amiss...

**Comment by brandonkelly** [comment]
Sorry, must have gotten the Sprout version number wrong; I was just looking at recent releases on GitHub. It’s expected that the error would occur after migrations were done, as it happens when Craft is updating the project config. My understanding is that the object Sprout tries to save to the project config was not intentional, so yeah you shouldn't be in any trouble after receiving the error, so long as there weren’t any other project config-related changes that weren’t able to get synced at the same time.
