### ISSUE TITLE
Duplicate slug is not incrementing

### ISSUE THREAD

**Issue by tinchalamo** [craftcms/cms#5064]
### Description
Saving a new entry with the same title as an old entry generates a duplicate slug rather than incrementing up to a new slug.

### Steps to reproduce

1. Create a new entry called "Testing"
2. Verify slug is `testing`
3. Create another entry called "Testing"
4. Generated slug is `testing`

### Additional info

- Craft version: 3.3.7
- PHP version: 7.3.9
- Database driver & version: MySQL 5.5.5
- Plugins & versions:
    "craftcms/redactor": "2.4.0",
    "mmikkel/incognito-field": "1.1.1.1",
    "rias/craft-position-fieldtype": "1.0.14",
    "verbb/super-table": "2.3.0",
    "marionnewlevant/match-input": "v2.0.1",
    "fruitstudios/linkit": "1.1.11",
    "nfourtythree/entriessubset": "1.2.2",
    "craftcms/aws-s3": "1.2.5",
    "doublesecretagency/craft-cpcss": "2.2.0",
    "craftcms/store-hours": "2.1.1.1",
    "elivz/craft-single-cat": "1.2.1",
    "fortrabbit/craft-copy": "1.0.0-RC7",
    "aelvan/preparse-field": "v1.1.0",
    "rias/craft-password-policy": "1.0.4",
    "craftcms/element-api": "2.6.0",
    "craftcms/feed-me": "4.1.2",
    "verbb/workflow": "1.2.3",
    "robuust/craft-reverserelations": "1.1.5",
    "mmikkel/cp-field-inspect": "1.0.6",
    "doublesecretagency/craft-inventory": "2.0.3",
    "fortrabbit/yii-memcached": "^1.0",
    "putyourlightson/craft-sendgrid": "1.1.1",
    "doublesecretagency/craft-cpjs": "2.2.0",
    "doublesecretagency/craft-cpbodyclasses": "2.1.1",
    "aelvan/imager": "v2.3.0",
    "craftcms/webhooks": "2.2.0"

**Comment by tinchalamo** [comment]
Looks like this is related to turning on `headlessMode`.

**Comment by billythekid** [comment]
@tinchalamo slugs only increment if they're used in the URL I believe. So headless mode or not, if your section entries don't have URLs (or the slug isn't used as part of the url, I think) the slug won't be forced to be unique. The unique identifiers are UID and entry ID.

**Comment by tinchalamo** [comment]
In talking to the Craft team this is expected behavior when using headless mode.

> Craft has never cared about whether slugs themselves are unique; only that the resulting URI is unique. And when running in headless mode, or any time you have a section that doesn't have an entry URI, there's no URI to ensure uniqueness on.

[It's expected to change in 3.4](https://github.com/craftcms/cms/issues/4520#issuecomment-531040417).

**Comment by ryanpcmcquen** [comment]
This is a serious, breaking change introduced in a minor update to Craft ...

Some of us use the slugs in other environments beyond our preview targets but still want headless mode. There should at least be a config option to ensure unique uris.

**Comment by brandonkelly** [comment]
@ryanpcmcquen Well, it wasn’t a breaking change; the entire concept of headless mode was introduced in 3.3, so you have to opt into the change in behavior. However it’s already been fixed in 3.4, per https://github.com/craftcms/cms/issues/4520#issuecomment-531040417.

**Comment by ryanpcmcquen** [comment]
@brandonkelly, I am running Craft 3.4.2 locally.

I can still duplicate an entry with a preview target of `{uri}` or `{slug}`, and the slug does not change (meaning we get dupes still). Is there something I am missing?

**Comment by brandonkelly** [comment]
Craft only cares about unique **URIs**, not slugs. And if the URI format contains a `{slug}` token, it will increment the slug as a way of finding a unique URI. So you will need to check your section’s settings and make sure you’ve given it an Entry URI Format – ideally one that contains `{slug}`.

**Comment by ryanpcmcquen** [comment]
@brandonkelly, I've given it a uri format containing both `{uri}` and `{slug}`, only `{uri}`, and only `{slug}`, the results are the same every time. It still isn't bothering to increment the slug, so I am getting duplicate URIs.

**Comment by brandonkelly** [comment]
Are you sure you’re looking at the **Entry URI Format** setting – not the preview target URL?

![A section’s site settings, with an arrow pointed toward the Entry URI Format column](https://user-images.githubusercontent.com/47792/73703299-4d14a180-46a4-11ea-81a5-31278c8e5684.png)

**Comment by ryanpcmcquen** [comment]
@brandonkelly, I did set the Entry URI (to `{slug}`) as well. It was still duplicating slugs but it isn't now after forcing a project config sync (it is weird because I had already saved the entry format, but forcing the sync seems to have _actually_ applied the change). I did also update to 3.4.3, so maybe it was something there as well.

Is there actually a scenario where duplicate slugs are desired? Seems like the default behavior should be not to duplicate slugs/URIs, rather than the inverse.

**Comment by brandonkelly** [comment]
Yep, lots of cases. Craft 1.0 actually did enforce slug uniqueness, and a ton of people requested that they be allowed to create duplicates.

**Comment by ryanpcmcquen** [comment]
Nevermind, I can still reproduce the slug duplication even with the Entry URI format, here's a recording showing the behavior:
![duplicate_slugs_in_3 4 3_again](https://user-images.githubusercontent.com/772937/73787630-8d315e00-4750-11ea-9ee4-3f0f04661ec6.gif)

**Comment by ryanpcmcquen** [comment]
@brandonkelly, here's a screenshot of the section config as well in case I am missing something there:
![Screen Shot 2020-02-04 at 12 40 15 PM](https://user-images.githubusercontent.com/772937/73790522-79d4c180-4755-11ea-9a26-1ec5345f761e.png)

**Comment by brandonkelly** [comment]
Do you have the [maxSlugIncrement](https://docs.craftcms.com/v3/config/config-settings.html#maxslugincrement) config setting set to `0` by chance? There is a special case where when duplicating an element, URI validation errors are ignored, so perhaps that’s happening here.

https://github.com/craftcms/cms/blob/8436bfe373e81a2cc9d551feb4f9bad8d0fbdefb/src/services/Elements.php#L761-L764

I’ve been thinking that maybe it makes sense to disable all elements by default when they are duplicated via that “Duplicate” element action. This is another good reason we should probably do that.

**Comment by ryanpcmcquen** [comment]
@brandonkelly, we don't have that setting in our codebase at all, which means we should have the default of `100`.

**Comment by brandonkelly** [comment]
In that case I’m a little stumped. I’m not able to reproduce that on my end. Can you send your `composer.json` and `composer.lock` files, and a database backup (or at least your `project.yaml` file), over to support@craftcms.com, so I can try reproducing it with those?

**Comment by ryanpcmcquen** [comment]
@brandonkelly, thanks! I just sent it over.
