### ISSUE TITLE
Unknown column 'config' in 'field list' on Craft 2 -> 3 upgrade

### ISSUE THREAD

**Issue by timkelty** [craftcms/cms#5391]
### Steps to reproduce

1.  Import a craft 2 database into a craft 3.4.x codebase
2. run `craft migrate/all` to start upgrade

```
Exception 'yii\db\Exception' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'config' in 'field list'
The SQL being executed was: SELECT `config`
FROM `craft_info`
LIMIT 1'

in /app/vendor/composer/yiisoft/yii2/db/Schema.php:674

Error Info:
Array
(
    [0] => 42S22
    [1] => 1054
    [2] => Unknown column 'config' in 'field list'
)

Stack trace:
#0 /app/vendor/composer/yiisoft/yii2/db/Command.php(1295): yii\db\Schema->convertException(Object(PDOException), 'SELECT `config`...')
#1 /app/vendor/composer/yiisoft/yii2/db/Command.php(1158): yii\db\Command->internalExecute('SELECT `config`...')
#2 /app/vendor/composer/yiisoft/yii2/db/Command.php(425): yii\db\Command->queryInternal('fetchColumn', 0)
#3 /app/vendor/composer/yiisoft/yii2/db/Query.php(291): yii\db\Command->queryScalar()
#4 /app/vendor/composer/craftcms/cms/src/db/Query.php(197): yii\db\Query->scalar(NULL)
#5 /app/vendor/composer/craftcms/cms/src/services/ProjectConfig.php(1436): craft\db\Query->scalar()
#6 /app/vendor/composer/craftcms/cms/src/services/ProjectConfig.php(360): craft\services\ProjectConfig->_getInternalConfigValue('system.timeZone')
#7 /app/vendor/composer/craftcms/cms/src/base/ApplicationTrait.php(1375): craft\services\ProjectConfig->get('system.timeZone')
#8 /app/vendor/composer/craftcms/cms/src/base/ApplicationTrait.php(1333): craft\console\Application->_setTimeZone()
#9 /app/vendor/composer/craftcms/cms/src/console/Application.php(63): craft\console\Application->_preInit()
#10 /app/vendor/composer/yiisoft/yii2/base/BaseObject.php(109): craft\console\Application->init()
#11 /app/vendor/composer/yiisoft/yii2/base/Application.php(206): yii\base\BaseObject->__construct(Array)
#12 /app/vendor/composer/yiisoft/yii2/console/Application.php(89): yii\base\Application->__construct(Array)
#13 /app/vendor/composer/craftcms/cms/src/console/Application.php(54): yii\console\Application->__construct(Array)
#14 [internal function]: craft\console\Application->__construct(Array)
#15 /app/vendor/composer/yiisoft/yii2/di/Container.php(400): ReflectionClass->newInstanceArgs(Array)
#16 /app/vendor/composer/yiisoft/yii2/di/Container.php(159): yii\di\Container->build('craft\\console\\A...', Array, Array)
#17 /app/vendor/composer/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('craft\\console\\A...', Array, Array)
#18 /app/vendor/composer/craftcms/cms/bootstrap/bootstrap.php(245): yii\BaseYii::createObject(Array)
#19 /app/vendor/composer/craftcms/cms/bootstrap/console.php(34): require('/app/vendor/com...')
#20 /app/bin/craft(6): require('/app/vendor/com...')
#21 {main}
[2020-01-02 20:03:11] craftcms.ERROR: PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'config' in 'field list' in /app/vendor/composer/yiisoft/yii2/db/Command.php:1290 Stack trace: #0 /app/vendor/composer/yiisoft/yii2/db/Command.php(1290): PDOStatement->execute() #1 /app/vendor/composer/yiisoft/yii2/db/Command.php(1158): yii\db\Command->internalExecute('SELECT `config`...') #2 /app/vendor/composer/yiisoft/yii2/db/Command.php(425): yii\db\Command->queryInternal('fetchColumn', 0) #3 /app/vendor/composer/yiisoft/yii2/db/Query.php(291): yii\db\Command->queryScalar() #4 /app/vendor/composer/craftcms/cms/src/db/Query.php(197): yii\db\Query->scalar(NULL) #5 /app/vendor/composer/craftcms/cms/src/services/ProjectConfig.php(1436): craft\db\Query->scalar() #6 /app/vendor/composer/craftcms/cms/src/services/ProjectConfig.php(360): craft\services\ProjectConfig->_getInternalConfigValue('system.timeZone') #7 /app/vendor/composer/craftcms/cms/src/base/ApplicationTrait.php(1375): craft\services\ProjectConfig->get('system.timeZone') #8 /app/vendor/composer/craftcms/cms/src/base/ApplicationTrait.php(1333): craft\console\Application->_setTimeZone() #9 /app/vendor/composer/craftcms/cms/src/console/Application.php(63): craft\console\Application->_preInit() #10 /app/vendor/composer/yiisoft/yii2/base/BaseObject.php(109): craft\console\Application->init() #11 /app/vendor/composer/yiisoft/yii2/base/Application.php(206): yii\base\BaseObject->__construct(Array) #12 /app/vendor/composer/yiisoft/yii2/console/Application.php(89): yii\base\Application->__construct(Array) #13 /app/vendor/composer/craftcms/cms/src/console/Application.php(54): yii\console\Application->__construct(Array) #14 [internal function]: craft\console\Application->__construct(Array) #15 /app/vendor/composer/yiisoft/yii2/di/Container.php(400): ReflectionClass->newInstanceArgs(Array) #16 /app/vendor/composer/yiisoft/yii2/di/Container.php(159): yii\di\Container->build('craft\\console\\A...', Array, Array) #17 /app/vendor/composer/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('craft\\console\\A...', Array, Array) #18 /app/vendor/composer/craftcms/cms/bootstrap/bootstrap.php(245): yii\BaseYii::createObject(Array) #19 /app/vendor/composer/craftcms/cms/bootstrap/console.php(34): require('/app/vendor/com...') #20 /app/bin/craft(6): require('/app/vendor/com...') #21 {main}  Next yii\db\Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'config' in 'field list' The SQL being executed was: SELECT `config` FROM `craft_info` LIMIT 1 in /app/vendor/composer/yiisoft/yii2/db/Schema.php:674 Stack trace: #0 /app/vendor/composer/yiisoft/yii2/db/Command.php(1295): yii\db\Schema->convertException(Object(PDOException), 'SELECT `config`...') #1 /app/vendor/composer/yiisoft/yii2/db/Command.php(1158): yii\db\Command->internalExecute('SELECT `config`...') #2 /app/vendor/composer/yiisoft/yii2/db/Command.php(425): yii\db\Command->queryInternal('fetchColumn', 0) #3 /app/vendor/composer/yiisoft/yii2/db/Query.php(291): yii\db\Command->queryScalar() #4 /app/vendor/composer/craftcms/cms/src/db/Query.php(197): yii\db\Query->scalar(NULL) #5 /app/vendor/composer/craftcms/cms/src/services/ProjectConfig.php(1436): craft\db\Query->scalar() #6 /app/vendor/composer/craftcms/cms/src/services/ProjectConfig.php(360): craft\services\ProjectConfig->_getInternalConfigValue('system.timeZone') #7 /app/vendor/composer/craftcms/cms/src/base/ApplicationTrait.php(1375): craft\services\ProjectConfig->get('system.timeZone') #8 /app/vendor/composer/craftcms/cms/src/base/ApplicationTrait.php(1333): craft\console\Application->_setTimeZone() #9 /app/vendor/composer/craftcms/cms/src/console/Application.php(63): craft\console\Application->_preInit() #10 /app/vendor/composer/yiisoft/yii2/base/BaseObject.php(109): craft\console\Application->init() #11 /app/vendor/composer/yiisoft/yii2/base/Application.php(206): yii\base\BaseObject->__construct(Array) #12 /app/vendor/composer/yiisoft/yii2/console/Application.php(89): yii\base\Application->__construct(Array) #13 /app/vendor/composer/craftcms/cms/src/console/Application.php(54): yii\console\Application->__construct(Array) #14 [internal function]: craft\console\Application->__construct(Array) #15 /app/vendor/composer/yiisoft/yii2/di/Container.php(400): ReflectionClass->newInstanceArgs(Array) #16 /app/vendor/composer/yiisoft/yii2/di/Container.php(159): yii\di\Container->build('craft\\console\\A...', Array, Array) #17 /app/vendor/composer/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('craft\\console\\A...', Array, Array) #18 /app/vendor/composer/craftcms/cms/bootstrap/bootstrap.php(245): yii\BaseYii::createObject(Array) #19 /app/vendor/composer/craftcms/cms/bootstrap/console.php(34): require('/app/vendor/com...') #20 /app/bin/craft(6): require('/app/vendor/com...') #21 {main} Additional Information: Array (     [0] => 42S22     [1] => 1054     [2] => Unknown column 'config' in 'field list' )  {"trace":[],"memory":14947848,"category":"yii\\db\\Exception","exception":"[object] (yii\\db\\Exception(code: 42): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'config' in 'field list'\nThe SQL being executed was: SELECT `config`\nFROM `craft_info`\nLIMIT 1 at /app/vendor/composer/yiisoft/yii2/db/Schema.php:674, PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'config' in 'field list' at /app/vendor/composer/yiisoft/yii2/db/Command.php:1290)"} []
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Additional info

- Craft version: 
```
            "version": "3.4.x-dev",
            "source": {
                "type": "git",
                "url": "https://github.com/craftcms/cms.git",
                "reference": "8a355e239c18849fc240c2998895f86de0582dd7"
            },
```

**Comment by timkelty** [comment]
I tried to bypass it by setting a timezone in my `config/general.php`, but I then got another SQL error: `Field 'siteName' doesn't have a default value`.

**Comment by andris-sevcenko** [comment]
This exact issue is resolved now on the `3.4` branch. However, there's a different error preventing upgrading now. Going to open a new issue for that.

**Comment by laurabennett** [comment]
I'm getting this same error updating from 3.3.3.20 to 3.4.
Database Exception – yii\db\Exception
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'config' in 'field list'
The SQL being executed was: SELECT `config`
FROM `info`
LIMIT 1
Error Info: Array
(
    [0] => 42S22
    [1] => 1054
    [2] => Unknown column 'config' in 'field list'
)
↵
Caused by: PDOException
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'config' in 'field list'
in C:\laragon\www\cherryhill\vendor\yiisoft\yii2\db\Command.php at line 1290

Should I open a new issue?

**Comment by msiemens** [comment]
> I'm getting this same error updating from 3.3.3.20 to 3.4.

Same for me!

**Comment by msiemens** [comment]
Seems like this issue occurs after migrations fail due failure of changing the project config because of read-only mode:

```
    > create table {{%projectconfig}} ... done (time: 0.004s)
    > batch insert into {{%projectconfig}} ... done (time: 0.005s)
    > batch insert into {{%projectconfig}} ... done (time: 0.003s)
    > batch insert into {{%projectconfig}} ... done (time: 0.003s)
    > batch insert into {{%projectconfig}} ... done (time: 0.002s)
    > batch insert into {{%projectconfig}} ... done (time: 0.002s)
    > batch insert into {{%projectconfig}} ... done (time: 0.002s)
    > batch insert into {{%projectconfig}} ... done (time: 0.004s)
    > batch insert into {{%projectconfig}} ... done (time: 0.004s)
    > batch insert into {{%projectconfig}} ... done (time: 0.004s)
    > batch insert into {{%projectconfig}} ... done (time: 0.003s)
    > batch insert into {{%projectconfig}} ... done (time: 0.004s)
    > batch insert into {{%projectconfig}} ... done (time: 0.003s)
    > batch insert into {{%projectconfig}} ... done (time: 0.002s)
    > drop column config from table {{%info}} ... done (time: 0.012s)
Exception: Changes to the project config are not possible while in read-only mode. (vendor/craftcms/cms/src/services/ProjectConfig.php:437)
```

**Comment by brandonkelly** [comment]
Can either of you find that error in your `storage/logs/web.log` file (or one of the older versions of `web.log` below it), and post the stack trace leading up to the error?

**Comment by timkelty** [comment]
I had the same thing, but then updated to the latest 3.4x and all was well

**Comment by TheFunkyMonk** [comment]
I am getting a different missing column, but hopefully this stack trace is helpful:

```
Database Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'channel' in 'field list'
The SQL being executed was: INSERT INTO queue (channel, job, description, timePushed, ttr, delay, priority) VALUES ('queue', 'O:41:\"nystudio107\\seomatic\\jobs\\GenerateSitemap\":8:{s:7:\"groupId\";s:1:\"1\";s:4:\"type\";s:7:\"section\";s:6:\"handle\";s:12:\"landingPages\";s:6:\"siteId\";i:1;s:16:\"queueJobCacheKey\";N;s:11:\"description\";N;s:30:\"\0craft\\queue\\BaseJob\0_progress\";i:0;s:35:\"\0craft\\queue\\BaseJob\0_progressLabel\";N;}', 'Generating landingPages sitemap', 1580239184, 300, 0, 1024)

Migration: craft\migrations\m190913_152146_update_preview_targets

Output:

Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'channel' in 'field list'
The SQL being executed was: INSERT INTO queue (channel, job, description, timePushed, ttr, delay, priority) VALUES ('queue', 'O:41:\"nystudio107\\seomatic\\jobs\\GenerateSitemap\":8:{s:7:\"groupId\";s:1:\"1\";s:4:\"type\";s:7:\"section\";s:6:\"handle\";s:12:\"landingPages\";s:6:\"siteId\";i:1;s:16:\"queueJobCacheKey\";N;s:11:\"description\";N;s:30:\"\0craft\\queue\\BaseJob\0_progress\";i:0;s:35:\"\0craft\\queue\\BaseJob\0_progressLabel\";N;}', 'Generating landingPages sitemap', 1580239184, 300, 0, 1024)  /app/vendor/yiisoft/yii2/db/Schema.php:674)
#0 /app/vendor/yiisoft/yii2/db/Command.php(1295): yii\db\Schema->convertException(Object(PDOException), 'INSERT INTO qu...')
#1 /app/vendor/yiisoft/yii2/db/Command.php(1091): yii\db\Command->internalExecute('INSERT INTO qu...')
#2 /app/vendor/craftcms/cms/src/queue/Queue.php(536): yii\db\Command->execute()
#3 /app/vendor/yiisoft/yii2-queue/src/Queue.php(196): craft\queue\Queue->pushMessage('O:41:"nystudio1...', 300, 0, NULL)
#4 /app/vendor/craftcms/cms/src/queue/Queue.php(173): yii\queue\Queue->push(Object(nystudio107\seomatic\jobs\GenerateSitemap))
#5 /app/vendor/nystudio107/craft-seomatic/src/services/Sitemaps.php(436): craft\queue\Queue->push(Object(nystudio107\seomatic\jobs\GenerateSitemap))
#6 /app/vendor/nystudio107/craft-seomatic/src/services/MetaBundles.php(325): nystudio107\seomatic\services\Sitemaps->invalidateSitemapCache('landingPages', 1, 'section')
#7 /app/vendor/nystudio107/craft-seomatic/src/seoelements/SeoEntry.php(121): nystudio107\seomatic\services\MetaBundles->invalidateMetaBundleById('section', 1, false)
#8 [internal function]: nystudio107\seomatic\seoelements\SeoEntry::nystudio107\seomatic\seoelements\{closure}(Object(craft\events\SectionEvent))
#9 /app/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Object(Closure), Object(craft\events\SectionEvent))
#10 /app/vendor/yiisoft/yii2/base/Component.php(636): yii\base\Event::trigger('craft\\services\\...', 'afterSaveSectio...', Object(craft\events\SectionEvent))
#11 /app/vendor/craftcms/cms/src/services/Sections.php(762): yii\base\Component->trigger('afterSaveSectio...', Object(craft\events\SectionEvent))
#12 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(1083): craft\services\Sections->handleChangedSection(Object(craft\events\ConfigEvent))
#13 [internal function]: craft\services\ProjectConfig->handleChangeEvent(Object(craft\events\ConfigEvent))
#14 /app/vendor/yiisoft/yii2/base/Component.php(627): call_user_func(Array, Object(craft\events\ConfigEvent))
#15 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(657): yii\base\Component->trigger('updateItem', Object(craft\events\ConfigEvent))
#16 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(1073): craft\services\ProjectConfig->processConfigChanges('sections.b58fa4...')
#17 [internal function]: craft\services\ProjectConfig->handleChangeEvent(Object(craft\events\ConfigEvent))
#18 /app/vendor/yiisoft/yii2/base/Component.php(627): call_user_func(Array, Object(craft\events\ConfigEvent))
#19 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(654): yii\base\Component->trigger('addItem', Object(craft\events\ConfigEvent))
#20 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(478): craft\services\ProjectConfig->processConfigChanges('sections.b58fa4...', true, '')
#21 /app/vendor/craftcms/cms/src/migrations/m190913_152146_update_preview_targets.php(54): craft\services\ProjectConfig->set('sections.b58fa4...', Array)
#22 /app/vendor/craftcms/cms/src/db/Migration.php(52): craft\migrations\m190913_152146_update_preview_targets->safeUp()
#23 /app/vendor/craftcms/cms/src/db/MigrationManager.php(233): craft\db\Migration->up(true)
#24 /app/vendor/craftcms/cms/src/db/MigrationManager.php(153): craft\db\MigrationManager->migrateUp(Object(craft\migrations\m190913_152146_update_preview_targets))
#25 /app/vendor/craftcms/cms/src/services/Updates.php(225): craft\db\MigrationManager->up()
#26 /app/vendor/craftcms/cms/src/controllers/BaseUpdaterController.php(510): craft\services\Updates->runMigrations(Array)
#27 /app/vendor/craftcms/cms/src/controllers/UpdaterController.php(203): craft\controllers\BaseUpdaterController->runMigrations(Array, 'restore-db')
#28 [internal function]: craft\controllers\UpdaterController->actionMigrate()
#29 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#30 /app/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#31 /app/vendor/craftcms/cms/src/web/Controller.php(178): yii\base\Controller->runAction('migrate', Array)
#32 /app/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('migrate', Array)
#33 /app/vendor/craftcms/cms/src/web/Application.php(290): yii\base\Module->runAction('updater/migrate', Array)
#34 /app/vendor/craftcms/cms/src/web/Application.php(645): craft\web\Application->runAction('updater/migrate')
#35 /app/vendor/craftcms/cms/src/web/Application.php(222): craft\web\Application->_processUpdateLogic(Object(craft\web\Request))
#36 /app/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#37 /app/web/index.php(21): yii\base\Application->run()
#38 {main}
```

**Comment by laurabennett** [comment]
I'm on dev environment so I don't think it's in read-only mode. Does this help or would you like the entire file?

Next yii\db\Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'config' in 'field list'
The SQL being executed was: SELECT `config`
FROM `info`
LIMIT 1 in C:\laragon\www\cherryhill\vendor\yiisoft\yii2\db\Schema.php:674
Stack trace:
#0 C:\laragon\www\cherryhill\vendor\yiisoft\yii2\db\Command.php(1295): yii\db\Schema->convertException(Object(PDOException), 'SELECT `config`...')
#1 C:\laragon\www\cherryhill\vendor\yiisoft\yii2\db\Command.php(1158): yii\db\Command->internalExecute('SELECT `config`...')
#2 C:\laragon\www\cherryhill\vendor\yiisoft\yii2\db\Command.php(425): yii\db\Command->queryInternal('fetchColumn', 0)
#3 C:\laragon\www\cherryhill\vendor\yiisoft\yii2\db\Query.php(291): yii\db\Command->queryScalar()
#4 C:\laragon\www\cherryhill\vendor\craftcms\cms\src\db\Query.php(188): yii\db\Query->scalar(NULL)
#5 C:\laragon\www\cherryhill\vendor\craftcms\cms\src\services\ProjectConfig.php(1710): craft\db\Query->scalar()
#6 C:\laragon\www\cherryhill\vendor\craftcms\cms\src\services\ProjectConfig.php(1604): craft\services\ProjectConfig->_loadInternalConfigData()
#7 C:\laragon\www\cherryhill\vendor\craftcms\cms\src\services\ProjectConfig.php(1593): craft\services\ProjectConfig->_getStoredConfig()
#8 C:\laragon\www\cherryhill\vendor\craftcms\cms\src\services\ProjectConfig.php(397): craft\services\ProjectConfig->_getLoadedConfig()
#9 C:\laragon\www\cherryhill\vendor\craftcms\cms\src\base\ApplicationTrait.php(1375): craft\services\ProjectConfig->get('system.timeZone')
#10 C:\laragon\www\cherryhill\vendor\craftcms\cms\src\base\ApplicationTrait.php(1333): craft\web\Application->_setTimeZone()
#11 C:\laragon\www\cherryhill\vendor\craftcms\cms\src\web\Application.php(100): craft\web\Application->_preInit()
#12 C:\laragon\www\cherryhill\vendor\yiisoft\yii2\base\BaseObject.php(109): craft\web\Application->init()
#13 C:\laragon\www\cherryhill\vendor\yiisoft\yii2\base\Application.php(206): yii\base\BaseObject->__construct(Array)
#14 C:\laragon\www\cherryhill\vendor\craftcms\cms\src\web\Application.php(91): yii\base\Application->__construct('[<span class="s...')
#15 [internal function]: craft\web\Application->__construct(Array)
#16 C:\laragon\www\cherryhill\vendor\yiisoft\yii2\di\Container.php(400): ReflectionClass->newInstanceArgs(Array)
#17 C:\laragon\www\cherryhill\vendor\yiisoft\yii2\di\Container.php(159): yii\di\Container->build('craft\\web\\Appli...', Array, Array)
#18 C:\laragon\www\cherryhill\vendor\yiisoft\yii2\BaseYii.php(365): yii\di\Container->get('craft\\web\\Appli...', Array, Array)
#19 C:\laragon\www\cherryhill\vendor\craftcms\cms\bootstrap\bootstrap.php(245): yii\BaseYii::createObject(Array)
#20 C:\laragon\www\cherryhill\vendor\craftcms\cms\bootstrap\web.php(51): require('C:\\laragon\\www\\...')
#21 C:\laragon\www\cherryhill\web\index.php(20): require('C:\\laragon\\www\\...')
#22 {main}
Additional Information:
Array
(
    [0] => 42S22
    [1] => 1054
    [2] => Unknown column 'config' in 'field list'
)

**Comment by msiemens** [comment]
> Can either of you find that error in your `storage/logs/web.log` file (or one of the older versions of `web.log` below it), and post the stack trace leading up to the error?

For me it was in `console.log`:

```
2020-01-28 19:59:36 [-][-][-][error][craft\errors\MigrateException] yii\base\NotSupportedException: Changes to the project config are not possible while in read-only mode. in vendor/craftcms/cms/src/services/ProjectConfig.php:437
Stack trace:
#0 vendor/craftcms/cms/src/migrations/m190913_152146_update_preview_targets.php(54): craft\services\ProjectConfig->set()
#1 vendor/craftcms/cms/src/db/Migration.php(52): craft\migrations\m190913_152146_update_preview_targets->safeUp()
#2 vendor/craftcms/cms/src/db/MigrationManager.php(233): craft\db\Migration->up()
#3 vendor/craftcms/cms/src/db/MigrationManager.php(153): craft\db\MigrationManager->migrateUp()
#4 vendor/craftcms/cms/src/services/Updates.php(225): craft\db\MigrationManager->up()
#5 vendor/craftcms/cms/src/console/controllers/MigrateController.php(255): craft\services\Updates->runMigrations()
#6 [internal function]: craft\console\controllers\MigrateController->actionAll()
#7 vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#8 vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams()
#9 vendor/yiisoft/yii2/console/Controller.php(164): yii\base\Controller->runAction()
#10 vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction()
#11 vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction()
#12 vendor/craftcms/cms/src/console/Application.php(87): yii\console\Application->runAction()
#13 vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction()
#14 vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest()
#15 craft(24): yii\base\Application->run()
#16 {main}
```

This was on the first run of the migration. When running the migration again it was:

```
Column not found: 1054 Unknown column 'config' in 'field list' in vendor/yiisoft/yii2/db/Command.php:1290
Stack trace:
#0 vendor/yiisoft/yii2/db/Command.php(1290): PDOStatement->execute()
#1 vendor/yiisoft/yii2/db/Command.php(1158): yii\db\Command->internalExecute()
#2 vendor/yiisoft/yii2/db/Command.php(425): yii\db\Command->queryInternal()
#3 vendor/yiisoft/yii2/db/Query.php(291): yii\db\Command->queryScalar()
#4 vendor/craftcms/cms/src/db/Query.php(188): yii\db\Query->scalar()
#5 vendor/craftcms/cms/src/services/ProjectConfig.php(1710): craft\db\Query->scalar()
#6 vendor/craftcms/cms/src/services/ProjectConfig.php(1604): craft\services\ProjectConfig->_loadInternalConfigData()
#7 vendor/craftcms/cms/src/services/ProjectConfig.php(1593): craft\services\ProjectConfig->_getStoredConfig()
#8 vendor/craftcms/cms/src/services/ProjectConfig.php(397): craft\services\ProjectConfig->_getLoadedConfig()
#9 vendor/craftcms/cms/src/base/ApplicationTrait.php(1375): craft\services\ProjectConfig->get()
#10 vendor/craftcms/cms/src/base/ApplicationTrait.php(1333): craft\console\Application->_setTimeZone()
#11 vendor/craftcms/cms/src/console/Application.php(57): craft\console\Application->_preInit()
#12 vendor/yiisoft/yii2/base/BaseObject.php(109): craft\console\Application->init()
#13 vendor/yiisoft/yii2/base/Application.php(206): yii\base\BaseObject->__construct()
#14 vendor/yiisoft/yii2/console/Application.php(89): yii\base\Application->__construct()
#15 vendor/craftcms/cms/src/console/Application.php(48): yii\console\Application->__construct()
#16 [internal function]: craft\console\Application->__construct()
#17 vendor/yiisoft/yii2/di/Container.php(400): ReflectionClass->newInstanceArgs()
#18 vendor/yiisoft/yii2/di/Container.php(159): yii\di\Container->build()
#19 vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get()
#20 vendor/craftcms/cms/bootstrap/bootstrap.php(245): yii\BaseYii::createObject()
#21 vendor/craftcms/cms/bootstrap/console.php(43): require('/mnt/web309/c0/...')
#22 craft(23): require('/mnt/web309/c0/...')
#23 {main}
```

**Comment by msiemens** [comment]
I think I got it: When running `m190913_152146_update_preview_targets`, the migration tries to change the project config:
https://github.com/craftcms/cms/blob/ad53b26c09659616c538f4f88abad60e05812049/src/migrations/m190913_152146_update_preview_targets.php#L54

This fails for me because on `allowAdminChanges` is set to `false`. Thus the upgrade of Craft fails and it thinks it's still on version 3.3.x. But then reading the project config in `ProjectConfig.php` fails:

https://github.com/craftcms/cms/blob/ad53b26c09659616c538f4f88abad60e05812049/src/services/ProjectConfig.php#L1706-L1723

This fails because the migration to move the project config to the `projectconfig` table has already been executed even though the upgrade to v3.4 failed.

**Comment by brandonkelly** [comment]
@laurabennett Any chance you can send us your `composer.json` and `composer.lock` files, plus a database backup from before your update, over to support@craftcms.com ?

**Comment by brandonkelly** [comment]
> This fails for me because on `allowAdminChanges` is set to `false`. Thus the upgrade of Craft fails and it thinks it's still on version 3.3.x. But then reading the project config in `craft\services\ProjectConfig` fails:

@msiemens When `allowAdminChanges => false`, it’s expected that you are on an environment where updates are deployed along with new `config/project.yaml` files, which would have prevented that code from running in the first place.

https://github.com/craftcms/cms/blob/ad53b26c09659616c538f4f88abad60e05812049/src/migrations/m190913_152146_update_preview_targets.php#L21-L26

Is that not the case for you? You just have `allowAdminChanges => false` without pairing it with `useProjectConfigFile => true` (and deploying a `config/project.yaml` file)?

**Comment by brandonkelly** [comment]
> EDIT: I commented out the lines from `ProjectConfig.php` and re-ran the migrations and it worked and the upgrade to v3.4 was successful.

@msiemens Please just revert to Craft 3.3 and a pre-update database backup. There’s a high likelihood that something didn’t get migrated properly for you, and hacking around the errors is just going to cause more issues down the road.

**Comment by msiemens** [comment]
> @msiemens When `allowAdminChanges => false`, it’s expected that you are on an environment where updates are deployed along with new `config/project.yaml` files, which would have prevented that code from running in the first place.

I always upgrade Craft and run the migrations on the dev environment first and then sync the `project.yml` to the production instance and execute migrations + project config sync there. I have àllowAdminChanges => true` and also `useProjectConfigFile => true`.

Strangely enough, another project where I ran the upgrade with the same setup worked without issues.

**Comment by brandonkelly** [comment]
> then sync the `project.yml` to the production instance and execute migrations + project config sync there

@msiemens How are you doing that?

**Comment by msiemens** [comment]
> @msiemens How are you doing that?

Using `rsync` to update the source code (including all of `config/` and `vendor/`) and then running `./craft migrate/all && ./craft project-config/sync` on the server.

**Comment by brandonkelly** [comment]
Alright I believe we’ve gotten to the bottom of this.

We believe everyone experiencing the missing `config` column error would have gotten a different error about a missing `channel` column in the `queue` table first, and then the `config` error would have started occurring on subsequent requests.

We’ve just released Craft 3.4.0.1 with a fix for the `queue.channel` error (d4c34cb1), so this should be resolved for everyone updating to 3.4 going forward.

**If you have experienced an error updating to 3.4 already**, you **must** restore your database using a database backup from **before** updating to Craft 3.4, and then reattempt the update, going straight to 3.4.0.1 this time.

**Comment by leobauza** [comment]
@brandonkelly I still experiencing some issues when trying to update from `3.1.34` to `3.4.3`. 

```
Exception 'yii\db\Exception' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'config' in 'field list'
The SQL being executed was: SELECT `config`
FROM `info`
LIMIT 1'
in /var/www/app/vendor/yiisoft/yii2/db/Schema.php:674
Error Info:
Array
(
    [0] => 42S22
    [1] => 1054
    [2] => Unknown column 'config' in 'field list'
)
```

Some more details:

- I am able to run the update fine in my dev environment (locally) but when I try to deploy it to staging I get the error above, and I see "an internal server error ocurred" if I open the front-end of admin sections of the site. We are using the project config so one of the differences is that `allowAdminChanges` is set to false in staging (I know that was mentioned earlier in the ticket, not sure if it's relevant.)
- I am using the same DB locally and in my staging environment
- I am first updating to `3.1.34.3` because I get the message "You’ve reached a breakpoint! More updates will become available after you install Craft CMS 3.1.34.3."
- I tried to run `project-config/rebuild` in between the upgrade to `3.1.34.3` and `3.4.3` since it was mentioned in the changelog

thanks in advance for your help

**Comment by brandonkelly** [comment]
@leobauza As I said in my last comment,

> We believe everyone experiencing the missing `config` column error would have gotten a different error about a missing `channel` column in the `queue` table first, and then the `config` error would have started occurring on subsequent requests.

So you need to figure out what the original error was. If you’re not sure, please restore your database to a pre-update backup, and reattempt the update. Pay attention to the original error you get, and look for it in `storage/logs/`, and please post the full stack trace leading up to it **as a new GitHub issue**.

**Comment by olets** [comment]
I had to bring an old Craft 2 database into a site that has been upgraded to Craft 3, and hit a "column not found" error. This issue was the only relevant one in the first page of my search results so sharing what worked in case it helps others:


```shell
# import db and then
./craft migrate/all
./craft update
./craft migrate/all # was prompted to do this when I tried running `./craft project-config/apply`. ymmv
./craft project-config/apply
```

and then `./craft plugin/install` or enable via the CP any plugins new since the backup was made.

**Comment by brandonkelly** [comment]
@olets If you send the Craft 2 database backup over to support@craftcms.com, we can take a look.

**Comment by olets** [comment]
@brandonkelly I'm all set but thank you!
