### ISSUE TITLE
syntax error, unexpected end of file, expecting function (T_FUNCTION) or const (T_CONST)

### ISSUE THREAD

**Issue by nmann4789** [craftcms/cms#5434]
### Description

Receiving this error randomly across the site. It appears to be happening when AWS health checks are running in our ECS environment.

### Steps to reproduce

1. ? 
2.

### Additional info

- Craft version: 3.3.19
- PHP version: 7.2.20
- Database driver & version: MySQL 5.7.12
- Plugins & versions:

![image](https://user-images.githubusercontent.com/4096608/72368282-c33c6e80-36cb-11ea-8d23-1c3c8dee4c5d.png)

![image](https://user-images.githubusercontent.com/4096608/72368302-d0595d80-36cb-11ea-876a-314796c3a39a.png)

**Comment by brandonkelly** [comment]
If your environment is load-balanced, have you set up a centralized data cache, e.g. using Redis? https://docs.craftcms.com/v3/config/app.html#cache-component

**Comment by RyanRoberts** [comment]
One of my clients reported a problem that appears to come down to this error too, no load balancing or redis going on as far as I'm aware :/

**Comment by brandonkelly** [comment]
@RyanRoberts We have fixed similar bugs in recent Craft 3.3 releases, so make sure you’re running at least 3.3.18.4.

**Comment by RyanRoberts** [comment]
@brandonkelly It's actually at version 3.3.19 and happened again last night. We'll run the latest updates as see that's not the latest version any more.

@rossthomson89 want to post more details since you're managing the site?

**Comment by rossthomson89** [comment]
Just to add to @RyanRoberts comment above heres the error we got:

ParseError: syntax error, unexpected end of file, expecting function (T_FUNCTION) or const (T_CONST) in /home/sites/SITENAME/storage/runtime/compiled_classes/ContentBehavior.php:479

Seems very similar to the same issue [here](https://github.com/craftcms/cms/issues/3475) but we're still seeing it with Craft CMS 3.3.19

**Additional info**
Craft version: 3.3.19
PHP version: 7.2.25
Database driver & version: MySQL 5.6.45

This error appeared in the very early hours of the morning when no one was working on the site/CMS so I can only assume this error occurs when the server does some kind of security patch in the middle of the night?

Sorted the issue by deleting the vendor and storage folders on the server and then running a composer install. We've experienced this issue twice now and seems to occur on its own without any kind of interaction with the code, CMS updates or CMS changes.

**Comment by brandonkelly** [comment]
I’m able to reproduce similar errors if I manually delete part of `ContentBehavior.php` / `ElementQueryBehavior.php`. I suspect this is happening if one of those classes is autoloaded before a previous (and ongoing) request is finished writing it.

Going with that, I believe I’ve fixed this for Craft 3.4, by catching any throwables that occur when loading auto generated classes. (1ed3619c727cabcbabe28604b08dc752d57fc302) I’ve also simplified the dynamic class generation in general, by only creating a single `CustomFieldBehavior.php` rather than those other two classes (7a2124715f5174ad12b37d32e7f1b4a0ea715217), which should further reduce potential issues.

Both of those changes are in Craft 3.4.0-RC3, which is out now.
