### ISSUE TITLE
Matrix field no longer changes to dropdown to avoid getting cut off screen

### ISSUE THREAD

**Issue by mofman** [craftcms/cms#5577]
![Screen Shot 2020-02-04 at 11 15 21](https://user-images.githubusercontent.com/3038169/73740309-de852180-473f-11ea-9681-33e800fa4a5e.png)
### Steps to reproduce

1. Create a matrix field with a ton of options
2. Try using it in CMS

### Additional info

- Craft version: 3.4
- PHP version: 7.2
- Database driver & version:
- Plugins & versions:

**Comment by brandonkelly** [comment]
I’m not able to reproduce this, but suspect it is the same underlying issue as #5549, which was fixed in 3.4.2. Please make sure you’re on the latest release.

**Comment by mofman** [comment]
Appeare to be only happening with Firefox?

**Comment by brandonkelly** [comment]
Working fire in Firefox for me, too.

**Comment by mofman** [comment]
Confirmed broken in multiple FIrefox browsers in Craft 3.4.3

Also pulled latest commit 12a9b33a096a170412f36a854477fb5d28cbfa2c and still broken.

**Comment by brandonkelly** [comment]
Are you getting any JavaScript errors on the pageL

**Comment by mofman** [comment]
Nope, I sent you an invite to a site we're working on, if you would like to take a look at 'Tickets & Events' section under 'Content Block' tab, its happening on mutiple users using Firefox.

**Comment by brandonkelly** [comment]
Sorry, looking closer at your screenshot, this is the same underlying issue as #5574, which has been fixed for the next release. That’s why I couldn’t reproduce. (The issue isn’t that the buttons aren’t collapsing; the issue is that the entire content pane is expanding too wide.)

**Comment by brandonkelly** [comment]
Craft 3.4.4 is out now with that fix.

**Comment by mofman** [comment]
Great stuff! Thanks for that!
