### ISSUE TITLE
No plugin exists with the handle "{handle}"

### ISSUE THREAD

**Issue by engram-design** [craftcms/cms#7229]
### Description
I've found that often I come across this issue for a number of plugins. I don't believe its plugin-specific, but its also hard to nail down the cause. It seems related to the plugin not being installed properly, or some specific combination of project config. Running `./craft project-config/rebuild` usually fixes it.

However - I can reliably reproduce the issue, which _might_ help in dealing with whatever scenario we're facing with the following:

1. Pick a plugin - any plugin - and make sure its uninstalled.
2. Add the following to the base plugin class
```
public function afterInstall()
{
    Craft::dd('Test!');
}
```
3. Install the plugin through the CP (CLI would also work, but easier to see in CP).
4. You'll see "Test!" printed on the screen, stopping the install.
5. Refresh the page (and confirm the re-submit of the page) or navigate back to `/admin/settings/plugins`.
6. You'll now see a No plugin exists with the handle "{handle}" error screen.
7. Navigate back to the plugins page and the plugin will be disabled. You try to install it, and the error will keep coming up.
8. Run `./craft project-config/rebuild` which should succeed.
9. Ensure you remove your `afterInstall()` function.
10. Install the plugin which should work.

### Additional info
- Craft version: 3.5.10.1
- PHP version: 7.2

**Comment by brandonkelly** [comment]
Fixed for the next release!

**Comment by engram-design** [comment]
What a service 🥳

**Comment by brandonkelly** [comment]
Craft 3.5.17 is out now with this fix.

**Comment by engram-design** [comment]
Champ 👍

**Comment by nicbou** [comment]
It still occurs in Craft 3.6.15 and 3.6.17. `./craft project-config/rebuild` did not fix the problem.

    Invalid plugin: No plugin exists with the handle "ckeditor".

There are no references to ckeditor in the database dump, so there are no tables to delete (https://github.com/craftcms/feed-me/issues/519)

Installing it with `craft install/plugin ckeditor` failed with the same message. Installing it with `composer require craftcms/ckeditor` worked, but enabling the plugin resulted in this error:

     file_put_contents(/var/www/storage/config-deltas/delta.yaml): failed to open stream: Permission denied 

I fixed the permission issues with `chmod -R ...`, and the plugin is finally there.

That's a lot of trouble for such a simple operation, itself a fix for another thing that's broken (Redactor II). I love Craft, but damn...

**Comment by brandonkelly** [comment]
@nicbou Do you have any idea how you got the error in the first place? If you can track down the error in your logs (`storage/logs/`), there should be a stack trace that follows it.

Probably unrelated to this specific issue though, even though the ultimate error message may be the same.

**Comment by nicbou** [comment]
The permission problems are a recurring issue for me. I am almost certain that it's my fault. I run Craft inside docker, and I've fiddled with that setup a little too much.

**Comment by brandonkelly** [comment]
Feel free to email support@craftcms.com if you need any pointers – or ask in the `#devops` channel in our Discord server (https://craftcms.com/discord).
