### ISSUE TITLE
Dynamic sending of account activation email does not add the correct localized link

### ISSUE THREAD

**Issue by romainpoirier** [craftcms/cms#7501]
### Description

I'm notifying pending users using a custom controller. The script is called by a cron job from an action URL, that loop through pending users:
```
$users = User::find()->status('pending')->limit(null)->all();
foreach ($users as $user) Craft::$app->getUsers()->sendActivationEmail($user);
```

The problem here is that the action link inside the email redirects to the reset password page (defined by `setPasswordPath`) instead of the success page (defined by `activateAccountSuccessPath`). Furthermore, it is not served using the language of the created user.

This wrong redirect happens even if `verificationCodeDuration` and `defaultTokenDuration` are setup for a very comfortable value, and even if the cron job test is done just after the user account creation.

After exploring the Craft source code, I found how to send the email using the correct action link like this:
```
foreach ($users as $user) {
    $url = Craft::$app->getUsers()->getEmailVerifyUrl($user);
    Craft::$app->getMailer()
        ->composeFromKey('account_activation', ['link' => Template::raw($url)])
        ->setTo($user)
        ->send();
}
```

But from this, the problem is that the link in this email redirect to the website using the default language, not the one defined un the `userLanguage` setting.

I tried to force the language of this link by adding this just before the `$url` setting within the loop: `Craft::$app->language = $user->userLanguage ?? Craft::$app->language`, but this does nothing more.

### Additional info

- Craft version: Craft Pro 3.5.19.1
- PHP version: 7.1.25
- Database driver & version: PostgreSQL 9.5.24

**Comment by brandonkelly** [comment]
> The problem here is that the action link inside the email redirects to the reset password page (defined by `setPasswordPath`) instead of the success page (defined by `activateAccountSuccessPath`). Furthermore, it is not served using the language of the created user.

That is expected. `setPasswordPath` is the path to the set-password page, which they must do in order to activate their account. `activateAccountSuccessPath` is where they should be redirected _after_ they’ve activated their account (hence the “`Success`”).

> But from this, the problem is that the link in this email redirect to the website using the default language, not the one defined un the `userLanguage` setting.

It’s based on the currently requested site by default.

What is `userLanguage` – a custom field? Craft doesn’t have any `userLanguage` properties, or `getUserLanguage()` getter methods.

**Comment by romainpoirier** [comment]
I don't think `setPasswordPath` is necessary in that case, as the password is defined by the user during the user registration process. This links should probably directs straight to `activateAccountSuccessPath`.

Yes, `userLanguage` is a custom field to define the user's preferred language (saved during the registration).
Is there any way to defined the site version of the activation link in order to match the user preference in that case?
Even if I force the value of `Craft::$app->language` that doesn't not seems to works.

**Comment by brandonkelly** [comment]
Hm… if the password is set then you should be getting a URL based on the `verifyEmailPath` config setting, not `setPasswordPath`.

https://github.com/craftcms/cms/blob/8b0dee8ebc864059a98eab9fb6721ccda1237979/src/services/Users.php#L339-L346

**Comment by brandonkelly** [comment]
> * Even if the pending user hasn't a password empty row in the DB, this value is empty when printed;

Ah, this is happening because user queries don’t actually select the `password` value by default (as it’s generally not needed).

Change this line:

```php
$users = User::find()->status('pending')->limit(null)->all();
```

to:

```php
$users = User::find()
    ->addSelect(['users.password'])
    ->status('pending')
    ->all();
```

That should solve this for you.

**Comment by romainpoirier** [comment]
Thank you @brandonkelly! Now using `addSelect(['users.password'])` the `Craft::$app->getUsers()->sendActivationEmail($user)` function redirects to the correct activation link (`activateAccountSuccessPath` instead of `setPasswordPath`). First problem solved ✔️

Unfortunately, this activation link still fails to redirect to the correct site version (defined here by the `userLanguage` custom field).

This happens even if the language is forced within the loop:
```
foreach ($users as $user) {
    Craft::$app->language = $user->userLanguage;
    Craft::$app->getUsers()->sendActivationEmail($user);
}
```

I tried to update the `$user->userLanguage` & `$user->language` values, but they are in read-only mode only. And the locale can't be force as a parameter in `sendActivationEmail()`.

So how to deal with the user locale in that case where there isn't a currently requested site by default (as the controller is called from a cron), where we can't update the user preferred language, and where can't force the notification language?

**Comment by brandonkelly** [comment]
> First problem solved ✔️

Great 🎉 

> Unfortunately, this activation link still fails to redirect to the correct site version (defined here by the `userLanguage` custom field).

I’m guessing the issue here is that current application language is only used when the user doesn’t have a preferred language selected in their control panel preferences, and only if the message is being sent from the front end:

https://github.com/craftcms/cms/blob/8b0dee8ebc864059a98eab9fb6721ccda1237979/src/mail/Message.php#L76-L81

https://github.com/craftcms/cms/blob/8b0dee8ebc864059a98eab9fb6721ccda1237979/src/mail/Mailer.php#L93-L98

We just released Craft 3.6.5 with a new `EVENT_BEFORE_PREP` event to Craft’s mailer, which you can hook into from your module in order to override the message language based on the user’s `userLanguage` custom field:

```php
use craft\mail\Mailer;
use craft\mail\Message;
use yii\base\Event;
use yii\mail\MailEvent;

Event::on(
    Mailer::class,
    Mailer::EVENT_BEFORE_PREP,
    function (MailEvent $event) {
        // Set the message to the userLanguage if there is one
        if (
            $event->message instanceof Message &&
            isset($event->message->variables['user']) &&
            $event->message->variables['user']->userLanguage
        ) {
            $event->message->language = $event->message->variables['user']->userLanguage;
        }
    }
);
```

You can also safely delete this line:

```php
Craft::$app->language = $user->userLanguage;
```

**Comment by romainpoirier** [comment]
Thank you @brandonkelly. But unfortunately, the notification email is still sent using the default site language.

The `EVENT_BEFORE_PREP` event was added at the bottom of all events in the main _Module.php_ file.

If I add an `exit;` just after `$event->message->language = $event->message->variables['user']->userLanguage;`, the script stops. So the language is correctly caught. I can also print `$user->userLanguage` value just before `Craft::$app->getUsers()->sendActivationEmail($user);`.

I thought the problem could be from my mailer setting in `config/app.php`:
```
'components' => [
    'mailer' => function() {
        // Get the stored email settings
        $settings = craft\helpers\App::mailSettings();

        // Override the transport adapter class
        $fromEmail = Craft::t('app', TEXT_FROM_EMAIL);
        $settings->fromEmail = (empty($fromEmail) || (!empty($fromEmail) && empty(filter_var(str_replace('+', '', $fromEmail), FILTER_VALIDATE_EMAIL)))) ? getenv('SYSTEM_EMAIL_ADDRESS') : $fromEmail;
        $settings->fromName = getenv('SENDER_NAME');
        $settings->template = getenv('HTML_EMAIL_TEMPLATE');
        $settings->transportType = craft\mandrill\MandrillAdapter::class;
        $settings->transportSettings = [
            'apiKey' => getenv('MANDRILL_API_KEY'),
            'subaccount' => getenv('MANDRILL_SUBACCOUNT')
        ];

        // Create a Mailer component config with these settings
        $config = craft\helpers\App::mailerConfig($settings);

        // Instantiate and return it
        return Craft::createObject($config);
    },
],
```

But even if I comment all of this, nothing change and the notification link target is still not localized.

**Comment by brandonkelly** [comment]
> But even if I comment all of this, nothing change and the notification link target is still not localized.

What exactly are you getting, and what are you expecting? The selected language is only going to determine which translated version of the message should be sent (see the language dropdown when editing a system message from **Utilities** → **System Messages**). It won’t affect what the URLs get set to.

**Comment by romainpoirier** [comment]
The mailer setting in `config/app.php` were an old setup that I ended up deleting  everything excepts `fromEmail` after new tests. Its only purpose is to get a custom `fromEmail` for system messages, because the sender email address should not be the same for each site versions.

Here is a more detailed scenario, and **where it goes wrong**:

1. User registers from NL site version, whereas primary site version is FR;
2. User receives the `account_activation` system message: content is in NL, `{{ link }}` targets NL site version;
3. User ignores this email, by not clicking on its link;
4. A controller is called periodically to re-send the activation email to pending users using `sendActivationEmail()`;
5. User receives the `account_activation` system message: content is in NL, **but `{{ link }}` targets FR site version**;

Within this controller, when I print the data:
- `user->userLanguage` returns `'nl'` and `user->preferredLanguage` returns `'nl'`, which are both correct;
- But `Craft::$app->getUsers()->getEmailVerifyUrl($user)` returns `/fr/verifyemail?code={code}&id={code)`, with wrong site version path (`/fr` instead of `/nl`);

That is probably why the `{{ link }}` sent from `sendActivationEmail()` is not using the correct site version.

Even if I hard-force the language using the new event:
```
Event::on(
    Mailer::class,
    Mailer::EVENT_BEFORE_PREP,
    function (MailEvent $event) {
        $event->message->language = 'nl';
    }
);
```
The system message content is in NL, but the `{{ link }}` still targets FR primary site version.

So how to localize the {{ link }}'s variable of `account_activation` system message in case it's not sent natively from Craft?

**Comment by brandonkelly** [comment]
Yeah OK, the URL is based on the _site_, not the language.

What you’ll need to do is change the current site, before calling `sendActivationEmail()`, based on the user’s preferred language.

```php
use yii\helpers\ArrayHelper;

// index all sites by their language
// NOTE: if two 2+ sites have the same language, the last one will be used here
$sitesByLanguage = ArrayHelper::index(Craft::$app->sites->getAllSites(), 'language');

$primarySite = Craft::$app->sites->getPrimarySite();

foreach ($users as $user) {
    // do we know the user's preferred language, and do we have a site that is set to it?
    if ($user->userLanguage && isset($sitesByLanguage[$user->userLanguage])) {
        Craft::$app->sites->setCurrentSite($sitesByLanguage[$user->userLanguage]);
    } else {
        Craft::$app->sites->setCurrentSite($primarySite);
    }

    Craft::$app->getUsers()->sendActivationEmail($user);
}
```

**Comment by romainpoirier** [comment]
Thank you @brandonkelly, this solution works perfectly in my controller! Problem solved ✔️

But I still have an issue with the `forgot_password` native system message using the new `EVENT_BEFORE_PREP` event.
When the email is sent from another locale on front-end and using the native action (`users/send-password-reset-email`), the link still targets the default primary site language instead of the forced language.

Example of reduced case:
```
Event::on(
    Mailer::class,
    Mailer::EVENT_BEFORE_PREP,
    function (MailEvent $event) {
        if ($event->message instanceof Message) {
            Craft::$app->sites->setCurrentSite('de');
            $event->message->language = 'de';
        }
    }
);
```

Here, while the email content is sent in Deutsch (DE) — the user language, the email `{link}` targets the Français (FR) primary site version. Any idea why?

**Comment by brandonkelly** [comment]
Well, again, this is because the URL is going to be based on the current _site_, not the language.

Is there only one “Forgot Password” page, on the primary site? Or does each site have its own? The URL should be based on whichever site was requested by the form.

**Comment by romainpoirier** [comment]
This page is set from the `setPasswordPath` config. It redirects to a Single page which is setup with a custom URI for each site (so each language).

Maybe it's a weird or useless case, but I was looking to always force the `{{ link }}` value based on the user preferred language, instead of the site where it is requested. In that case, the `EVENT_BEFORE_PREP` strangely doesn't work.

In 90% of our projects, we only have one site group where versions are just translated version of the primary site.

**Comment by brandonkelly** [comment]
`setPasswordPath` is just a URI path though. It will be appended to whatever the current site’s base URL is. So again, where is your “Forgot Password” page? Is there just one, or do you have one for each site?

**Comment by romainpoirier** [comment]
I'm sorry if I miss, misunderstood or misexplained something.

If `setPasswordPath` is set like this:
`'setPasswordPath' => 'actions/users/set-password'`
It targets the `actions/users/set-password.twig` template (which in my case extends the login page template) which is correct.

I also tried like this:
```
'setPasswordPath' => function() {
    return Entry::find()->section('myAccount')->one()->uri ?? null;
}
```
Where `myAccount` is a login page: it is a Single available in each site version, so for each language. Its content is localized.

But both are failing to load the expected site version, as the link in the email always targets the Primary site (I can see the `/fr` prefix in the URI, instead of `/de` when sent to a user set with `DE` preference or when `EVENT_BEFORE_PREP` is forced).

So the URI for `setPasswordPath` seems correct, but the wrong version is served because of this prefix.

**Comment by brandonkelly** [comment]
I still need to know where the “Forgot Password” page actually lives though…

**Comment by romainpoirier** [comment]
Sorry if I'm still not clear :
The “Forgot Password” lives within the login page (`Entry::find()->section('myAccount')->one()`) which is a `Single`.
This page shows the reset password form in a modal when it detects the `code` & `id` query parameters.
This is the only page, and it is setup and enabled for each (translated) site version (`FR`, `DE` & `EN`).

**Comment by brandonkelly** [comment]
And I take it that each site has its own Login page?

**Comment by romainpoirier** [comment]
Yes, each site has its own Login page. The Login page is the `myAccount` Single, which is setup and enabled for each site version.

**Comment by brandonkelly** [comment]
How is the modal submitting the password reset form?

**Comment by romainpoirier** [comment]
Using an AJAX submitted form: `$.post({ url: '/', …`,  and this tag within the form: `<input type="hidden" name="action" value="users/send-password-reset-email">`.

**Comment by brandonkelly** [comment]
Are the sites’ base URLs set identically to their selected languages?

**Comment by romainpoirier** [comment]
Yes they are.

**Comment by brandonkelly** [comment]
Hm… and you’ve verified that the Ajax request is going to the expected URLs?

**Comment by romainpoirier** [comment]
I can see in the Chrome DevTools that the _Request URL_ is going to `https://www.example.com/siteHandle` (where `siteHandle` is something like `en` or `nl`) with an action to `users/send-password-reset-email`.
