### ISSUE TITLE
Project config yaml comments inconsistently applied

### ISSUE THREAD

**Issue by timkelty** [craftcms/cms#7709]
### Description

The comments added from https://github.com/craftcms/cms/issues/7584 seem to not always be applied. `project-config/rebuild` seems to always add them, while changes in the CP don't.

### Steps to reproduce

1. Verify you have comments in your yaml
2. Create a new field in the CP
3. `git status` will reveal tons of changes, removing the human-readable comments after the UUID 

Curiously, if you preempt that whole process with a `./craft project-config/rebuild` (changing only the `dateModified`), everything works as expected, only the new field is added.

### Additional info

- Craft version: 3.6.10
- PHP version: 7.4.13

**Comment by andris-sevcenko** [comment]
If given a UID, it's unfeasible to traverse all the tables looking for the correct name, so Project Config builds its knowledge of UID => Name as it saves project config data. As it turns out, running a project rebuild is the easiest way to gain full knowledge of UID => Name pairs I'm one go, so there's that.

In the end, it comes down to the fact that in some environments, if project config rebuild has not been run, there's a very high chance of PC simply not knowing all the entities, as it writes out the config files.

Also, the comments FROM the YAML files are lost when parsing the file, so this information cannot be transferred between environments.
==========

Having said that, are you saying that you run a project config rebuild, then create a new field and that causes you to lose all the comments subsequently and this all happens in one environment? If so, then that would not be a known behavior.

**Comment by timkelty** [comment]
> Having said that, are you saying that you run a project config rebuild, then create a new field and that causes you to lose all the comments subsequently and this all happens in one environment?

Nope, if I first rebuild, all is well after the field save.

Looking at the db, I now see that things are being saved to `projectconfignames`. Does this sound like a reasonable explanation?

- The remote db doesn't have everything in `projectconfignames`, but also never gets a `rebuild` run.
- Since devs are pulling down dumps from this env, they experience the issue locally when saving a field
- If they run `rebuild` locally, the issue is fixed, however, next time they pull a fresh db, they'll experience the same thing.

If so, it would seem that running `rebuild` remotely (once) might fix the issue?

**Comment by andris-sevcenko** [comment]
> I wonder if it would make sense to also update projectconfignames on apply, which would prevent this from happening?

It is updated for the settings that are being processed, though.

**Comment by timkelty** [comment]
Gotcha. So it sounds like this is an artifact of upgrading to 3.6.8 (remotely), and not having run a `rebuild` on that env.

**Comment by andris-sevcenko** [comment]
Awesome, closing this one out, then. Let me know if you run into this again!

**Comment by nickdunn** [comment]
I must admit I've been seeing this too — two developers running identical builds with Docker — sometimes the field names disappear from the YAML e.g.

    settings:
      allowSelfRelations: false
      entryTypes:
    -    - fe0a752a-d9d2-4bdf-9a02-70e100d4131a # Statistic
    +    - fe0a752a-d9d2-4bdf-9a02-70e100d4131a
      limit: '1'
      localizeRelations: false
      selectionLabel: ''

(This is my local, running 3.6.10).

I also get intermittent switching between nulls and blank strings e.g.

    -childBlocks: ''
    +childBlocks: null
    field: f76a4a51-373e-4348-8af8-c54a6ff7ebbe # Page hero
    fieldLayouts:
      56774bed-ebb1-4845-841c-3b6b95686655:

**Comment by nickdunn** [comment]
And in some instances switching between single and double quotes, and new-lines for arrays:

    -childBlocks: ""
    +childBlocks: ''
    field: ca6e522f-3f8c-4df8-92fd-4854b0324fe9 # Page content
    fieldLayouts:
      a0d78949-460d-47b3-a433-15aae2a44dec:
        tabs:
    -      - elements:
    -          - fieldUid: 911f6f22-4370-465b-bb2a-76dee4eea04d # Heading
    -            instructions: ""
    -            label: ""
    -            required: "1"
    +      -
    +        elements:
    +          -
    +            fieldUid: 911f6f22-4370-465b-bb2a-76dee4eea04d # Heading
    +            instructions: ''
    +            label: ''
    +            required: '1'
                tip: null
                type: craft\fieldlayoutelements\CustomField
                warning: null
                width: 100
    -          - fieldUid: 993fab7e-29b5-49de-bdbc-2a8d701e5e71 # FAQs
    +          -
    +            fieldUid: 993fab7e-29b5-49de-bdbc-2a8d701e5e71 # FAQs
                instructions: null
                label: null
                required: false

**Comment by nickdunn** [comment]
I put this down to possible differences between both developer's machines... but given the environment is from Docker and Composer all versions of dependencies should be identical so I'd expect the config to be generated the same every time?

**Comment by timkelty** [comment]
@nickdunn did you trying running `project-config/rebuild` on the source database, and then having the developers pull that db?

**Comment by nickdunn** [comment]
Hmm no. We are two developers working locally, then applying project-config to a remote testing server. The testing server has `allowAdminChanges` disabled so we apply project-config changes there but never rebuild from it. The diffs above are between two the developer machines.

**Comment by andris-sevcenko** [comment]
> I must admit I've been seeing this too — two developers running identical builds with Docker — sometimes the field names disappear from the YAML e.g.

That's because the UID -> Project Config name is stored in the database - it gets built up over time for every change you set locally.  This was considered a reasonable inconvenience since it's a cosmetic thing only and can be remedied by rebuilding.

As far as your other things go - do you share the same composer.lock file? Craft has no say over newlines in arrays, for example, so that might be due to a difference in `symfony/yaml` versions, perhaps?

**Comment by nickdunn** [comment]
I guess I don’t understand why sometimes the comments in the YAML would disappear when goth developers have an up to date build of the site. Is that expected under some circumstances?

Yep we share the same composer.lock and the whole environment is built from a Dockerfile so they should be near identical. 

For what it’s worth, we’ve seen most of the diffs with the LinkIt field. Maybe there’s something specific to the way that field serialises itself. 

In noted that latest Craft version fixes some project config bugs so we’ll upgrade and see whether it resolves the issue.

**Comment by timkelty** [comment]
> Hmm no. We are two developers working locally, then applying project-config to a remote testing server. 

@nickdunn right, but as @andris-sevcenko mentioned, when you run rebuild, it will save all the UID → handle mappings to the database. Since you are never pushing your database upstream, fields that are missing mappings are the ones that keep causing your trouble.

So, I suspect if you run this on your remote env (once), and then have your developers pull a copy of that db, your issue will be resolved.

**Comment by andris-sevcenko** [comment]
@nickdunn yeah, that is likely the culprit here. Can you try rebuilding on the remote server and then see what's what with the comments in Yaml files, please?

Also, let's keep this issue focused on the comment thing - can you open a new issue for the project config changes happening for no reason? Ideally, it would be with some way to reproduce it.

**Comment by nickdunn** [comment]
> Also, let's keep this issue focused on the comment thing - can you open a new issue for the project config changes happening for no reason? Ideally, it would be with some way to reproduce it.

We diagnosed this! It was caused by a local VS Code YAML formatter touching the file, namely when resolving merge conflicts when two people made changes so the `dateModified` line would always conflict.

We've since upgraded to latest (`3.6.11.2`) and the other issues haven't reoccurred yet, so I'm going to assume this is fixed.

**Comment by andris-sevcenko** [comment]
@nickdunn wow, that one sounds annoying to debug. Glad you figured it out!

**Comment by brandonkelly** [comment]
@nickdunn The next time you have a `dateModified` conflict, you can run the following command to quickly resolve it:

```bash
> php craft project-config/touch
```

**Comment by darylknight** [comment]
This issue isn't fixed, I still periodically see comments added or removed, even when it's a solo project.

**Comment by brandonkelly** [comment]
I believe it happens when you pull a production database down, which maybe wasn’t populated with all the UID/name mappings.

If you run `php craft project-config/rebuild` on production, and then pull its DB down to all other environments, it should stop happening.

That said, I think we should consider storing those mappings directly in the project config data itself, so it’s portable across environments. Reopening with that in mind…

**Comment by andris-sevcenko** [comment]
This has been improved for Craft 3.7.

**Comment by leevigraham** [comment]
@brandonkelly @andris-sevcenko So to confirm there should always be comments in Craft 3.7+ ?

**Comment by andris-sevcenko** [comment]
They will no longer get lost sometimes when transferring between sites, but they are still only written down when encountered and the way to encounter them all is to do a rebuild. So, after a rebuild, they should always be there, yes.

**Comment by howells** [comment]
@andris-sevcenko @brandonkelly sorry to bring this up again, but I'm finding comments very inconsistently applied.

For example, if I rebuild a project on production, download that config and apply to my local environment (which doesn't have comments), then proceed to make some sort of change to my sections, the entire project config is rebuilt with comments. It makes confirming the changes made in git really difficult.

**Comment by howells** [comment]
@timkelty I got an email notification of your comment but can't see it here: but yes, did that step as described above.

**Comment by russback** [comment]
@brandonkelly just found that when running the Rebuild from within the Control Panel, all comments are removed. This is on Craft 4.2.3. Rebuilding via the command line adds the comments as expected.
